### ISSUE TITLE
Title > path in search

### ISSUE THREAD

**Issue by mathieutu** [bchatard/alfred-jetbrains#10]
Q | A
--- | ---
Workflow version | _1.0.5_
OSX Version | _17.7.0_
Alfred Version | _3.8.1_
JetBrains Product/Version | _PhpStorm / 2019.1_
Installation type | _JB Toolbox_

### Description
When searching for the project, the query will look in the path of project.

So if my query is present in all the projects paths, it will return all the projects.

The project name should be more important than the path.

Example of why it's wrong: 
<img width="560" alt="Screen Shot 2019-04-10 at 14 42 54" src="https://user-images.githubusercontent.com/11351322/55879545-2e866c80-5b9f-11e9-8a58-d7bb9120b31d.png">

Here, nothing changed with the query, but the mathieutu.dev project should be, at least, in first position.

Thanks.

**Comment by bchatard** [comment]
@mathieutu thanks for your report
Yes, it's an old issue. It's not easy to solve, so I use a "search engine" to address this issue
Can you install this pre-release:
`npm -g i @bchatard/alfred-jetbrains@next`

Let me know if it's better or not

**Comment by bchatard** [comment]
merged in master, you can install latest release. 
I will try to add customisation capabilities for the "search engine", to change default option.

**Comment by mathieutu** [comment]
Actually this is worst with the last version 😕

Here the `mathieutu.dev` project is less ranked when searching for `mathieutu`.
![2019-04-17 11 11 20](https://user-images.githubusercontent.com/11351322/56275771-a30e5d80-6101-11e9-82fe-5ca7726ff7f9.gif)

**Comment by bchatard** [comment]
ok, thanks for your feedback.
With my test, it's a little bit better, but it depends a lot of the "indexed data".
I will implement "search engine customisation" so we can optimise this part.

**Comment by bchatard** [comment]
Hi @mathieutu,

I add a customisation process for the search engine. Can you take a look on the latest version (and [related doc](https://github.com/bchatard/alfred-jetbrains/blob/master/doc/customisation/search.md) ?

Thanks,
