### ISSUE TITLE
Can't find IDEA projects

### ISSUE THREAD

**Issue by ArchCST** [bchatard/alfred-jetbrains#110]
**Describe the bug**
Alfred can't find all my projects, can only find one.

**Expected behavior**
Alfred list all my project.

**Screenshots**
<img width="510" alt="截屏2020-03-10下午2 08 21" src="https://user-images.githubusercontent.com/41679407/76284555-9b871280-62d8-11ea-933f-b661706e4fbc.png">
As you can see, there's only one project list in Alfred, the other IDEA is a Windows IDEA installed in a VM, you could ignore it.

At the meantime, when I try "idea xxxproject" in iTerm, it works, opened a IDEA window with xxxproject, so I assume it isn't a command-line tool issue.

Q | A
--- | ---
Workflow version | _1.1.3_
OSX Version | _10.15.3_
Alfred Version | _3.8.6_
JetBrains Product/Version | _IDEA / 2019.3.1_
Installation type | _classic .dmg / Caskroom / JB Toolbox_
Node version | _12.7.0_
NPM version | _6.13.4_

If any further test you need, please don't hesitate to ask, thank you very much.

**Comment by bchatard** [comment]
Hi,

Can you share the content of the `idea` shell script?

**Comment by ArchCST** [comment]
> Hi,
> 
> Can you share the content of the `idea` shell script?

What do you meat by content? How should I proceed?

![截屏2020-03-20上午11 18 03](https://user-images.githubusercontent.com/41679407/77133016-79418180-6a9c-11ea-8ded-8451189192db.png)

**Comment by bchatard** [comment]
Hi,

with the following command: `cat $(which idea)` (you can also do `cat $(which idea) | pbcopy` this will copy the result to your clipboard)

Can you also share the content of this file: `cat ~/Library/Preferences/IntelliJIdea2019.3/options/recentProjects.xml` (path may change depends on your Idea version). Please remove any sensitive data first.

Thanks,

**Comment by ArchCST** [comment]
Sorry for the delay, hard days...

# `cat $(which idea)` result:
```
#!/usr/bin/env python
# Copyright 2000-2019 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license.
# -*- coding: utf-8 -*-

import os
import socket
import struct
import sys
import traceback

# see com.intellij.idea.SocketLock for the server side of this interface

RUN_PATH = u'/Applications/IntelliJ IDEA.app'
CONFIG_PATH = u'/Users/cst/Library/Preferences/IntelliJIdea2019.3'
SYSTEM_PATH = u'/Users/cst/Library/Caches/IntelliJIdea2019.3'


def print_usage(cmd):
    print(('Usage:\n' +
           '  {0} -h | -? | --help\n' +
           '  {0} [project_dir] [-w|--wait]\n' +
           '  {0} [-l|--line line] [project_dir|--temp-project] [-w|--wait] file[:line]\n' +
           '  {0} diff <left> <right>\n' +
           '  {0} merge <local> <remote> [base] <merged>').format(cmd))


def write_to_sock(sock, data):
    if sys.version_info[0] >= 3:
        data = data.encode('utf-8')
    sock.send(struct.pack('>h', len(data)) + data)


def read_from_sock(sock):
    length = struct.unpack('>h', sock.recv(2))[0]
    return sock.recv(length).decode('utf-8')


def read_sequence_from_sock(sock):
    result = []
    while True:
        try:
            data = read_from_sock(sock)
            if data == '---':
                break
            result.append(data)
        except (socket.error, IOError) as e:
            print("I/O error({0}): {1} ({2})".format(e.errno, e.strerror, e))
            traceback.print_exception(*sys.exc_info())
            break
    return result


def process_args(argv):
    args = []

    skip_next = False
    for i, arg in enumerate(argv[1:]):
        if arg == '-h' or arg == '-?' or arg == '--help':
            print_usage(argv[0])
            exit(0)
        elif i == 0 and (arg == 'diff' or arg == 'merge' or arg == '--temp-project'):
            args.append(arg)
        elif arg == '-l' or arg == '--line':
            args.append(arg)
            skip_next = True
        elif arg == '-w' or arg == '--wait':
            args.append('--wait')
        elif skip_next:
            args.append(arg)
            skip_next = False
        else:
            path = arg
            if ':' in arg:
                file_path, line_number = arg.rsplit(':', 1)
                if line_number.isdigit():
                    args.append('-l')
                    args.append(line_number)
                    path = file_path
            args.append(os.path.abspath(path))

    return args


def try_activate_instance(args):
    port_path = os.path.join(CONFIG_PATH, 'port')
    token_path = os.path.join(SYSTEM_PATH, 'token')
    if not (os.path.exists(port_path) and os.path.exists(token_path)):
        return False

    try:
        with open(port_path) as pf:
            port = int(pf.read())
        with open(token_path) as tf:
            token = tf.read()
    except ValueError:
        return False

    s = socket.socket()
    s.settimeout(1.0)
    try:
        s.connect(('127.0.0.1', port))
    except (socket.error, IOError):
        return False

    paths = read_sequence_from_sock(s)
    found = CONFIG_PATH in paths

    if found:
        write_to_sock(s, 'activate ' + token + '\0' + os.getcwd() + '\0' + '\0'.join(args))

        s.settimeout(None)
        response = read_sequence_from_sock(s)
        if len(response) < 2 or response[0] != 'ok':
            print('bad response: ' + str(response))
            exit(1)

        if len(response) > 2:
            print(response[2])

        exit(int(response[1]))

    return False


def start_new_instance(args):
    if sys.platform == 'darwin':
        if len(args) > 0:
            args.insert(0, '--args')
        os.execvp('/usr/bin/open', ['-a', RUN_PATH] + args)
    else:
        bin_file = os.path.split(RUN_PATH)[1]
        os.execv(RUN_PATH, [bin_file] + args)


ide_args = process_args(sys.argv)
if not try_activate_instance(ide_args):
    start_new_instance(ide_args)
```

**Comment by linesh-simplicity** [comment]
@bchatard 
I'm encountering the same issue here: only one of my recent project is shown by the plugin. And I get some inspiration from this [comment](https://github.com/bchatard/alfred-jetbrains/issues/110#issuecomment-601569918), guessing maybe it's because I'm using WebStorm 2020.1 through the JetBrains Toolbox app and the recent files xml location has been changed to `~/Library/Application Support/JetBrains/WebStorm2020.1/options/recentProjects.xml` and that's why it's always the configs in `~/Library/Preferences/WebStorm2020.1/options/recentProjects.xml` always getting loaded(which indeed has the only one project that keeps showing by the plugin). 

Any workaround now for us to work with the Toolbox app or is there any plan to support Toolbox maybe in the near future? 

Thanks for the excellent plugin though.

**Comment by bchatard** [comment]
@linesh-simplicity please check latest version and also my [comment](https://github.com/bchatard/alfred-jetbrains/issues/115#issuecomment-609385563). Toollbox is supported since the beginning ;)

@ArchCST I need the content to this file, to understand where the issue can be: `cat ~/Library/Preferences/IntelliJIdea2019.3/options/recentProjects.xml` (path may change depends on your Idea version). Please remove any sensitive data first.

**Comment by azerbe** [comment]
Same Problem here. Using Intellij 2020.1.
I removed the old/unused recentProjects.xml files from `~/Library/Preferences` and nothing changed. Using the `idea` script generated by toolbox to `/usr/local/bin`.

```cat $(which idea)                                                                 
#!/bin/sh
# Generated by JetBrains Toolbox 1.17.6802 at 2020-04-25T19:08:28.301775

open -na "/Users/USERNAME/JetBrains/apps/IDEA-U/ch-0/201.6668.121/IntelliJ IDEA.app/Contents/MacOS/idea" --args "$@"
```

I dont want to share sensible informations about all my projects in the `recentProjects.xml` file to a public audience. But it seems that all my projects are populated in there. Atleast the ones that are not found by the script.

The funny story is, that on another mac it works just out of the box. It used to work on my main Laptop too, but it seems like something changed over time or it reads from a old projects file.

**Comment by azerbe** [comment]
Okay, it seems that there are differences in `recentProjectDirectories.xml` and `recentProjects.xml` in my Preferences Folder and I get the results from `recentProjectDirectories.xml` which is missing the other projects.

After removing the `recentProjectsDirectories.xml` everything is back working.

**Comment by bchatard** [comment]
hi @azerbe thanks for your feedback and troubleshooting :)

**Comment by AlexeyKorshun** [comment]
Hi @bchatard I use 1.4.0 version. But when I tried to open IDEA projects it says that "No project found". But it works fine for Android studio. IDEA 2020.2

**Comment by bchatard** [comment]
@AlexeyKorshun can you check https://github.com/bchatard/alfred-jetbrains/issues/157#issuecomment-692498224?

**Comment by AlexeyKorshun** [comment]
hm thx for link. can you tell which is directory I should delete?

**Comment by baixiaodong** [comment]
> recentProjectDirectories

where is this Folder  about recentProjectDirectories, can you show the full path ? thinks

**Comment by aprice42** [comment]
#157 fixed the issue for me to! After uninstalling the workflow there were still files in `/usr/local/lib/node_modules/@bchatard/alfred-jetbrains` after removing those and reinstalling it worked as expected again.  

Summary of steps to fix: 

```
npm uninstall -g @bchatard/alfred-jetbrains
rm -rf /usr/local/lib/node_modules/@bchatard/alfred-jetbrains
npm install -g @bchatard/alfred-jetbrains
```

Hope this helps!
