### ISSUE TITLE
Forced having to flush cache everytime new project is opened.

### ISSUE THREAD

**Issue by johnsintal** [bchatard/alfred-jetbrains#116]
I noticed I have to run `jb Clean Projects Cache` in order for a product to a newly opened project.

Is there a way to get the cache updated every so often? 

I did notice variables you can tweak `jb_project_cache_lifetime` and `jb_product_cache_lifetime` to a value like `30` seconds, however, it is not clear from the README which one affects the list of projects for a given product.

Based on my experimentation, I believe it's `jb_product_cache_lifetime` that refresh the list of available projects for a given product (i.e. `wstorm <new project>`) however, I am not sure how `jb_project_cache_lifetime` affects the workflow. It seems to contradict my understanding that 

> **jb_project_cache_lifetime**: cache lifetime in seconds for project list (one cache per app) [default: 3600 seconds]

since it was `jb_product_cache_lifetime=30` that made an impact of the list of projects available for a product and not `jb_project_cache_lifetime=30`

Can someone help me understand the specifics here?

![image](https://user-images.githubusercontent.com/2457368/78468985-ae7bdf80-76ea-11ea-84f8-9d702444932d.png)

**Comment by bchatard** [comment]
Hi,

I will take a look on this asap, but definitely a bug

**Comment by bchatard** [comment]
hi,

i just test the cache mechanism, an it works fine.

you can check your cache (and it's lifetime) in : `~/Library/Caches/com.runningwithcrayons.Alfred/Workflow\ Data/fr.chatard.jetbrains.workflow/cache.json`

can you take a look on this file between each call with a low cache lifetime?
