### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by lxy1992** [bchatard/alfred-jetbrains#13]
Q | A
--- | ---
Workflow version | _1.0.0_
OSX Version | _10.14.3_
Alfred Version | _3.8.2
JetBrains Product/Version | _PhpStorm / 2019.1_
Installation type | _classic .dmg / Caskroom / JB Toolbox_

### Description
Script Error:
![0EDCFDD2-5D53-40C3-A1A5-9BAEA5E00A76](https://user-images.githubusercontent.com/6184994/56032028-a09fb280-5d53-11e9-9c42-e753d5ebb0e4.png)

### Step to reproduce
Just follow the instruction to install this tool.
Open Alfred to use the keyword "pycharm", then I end up with this error. 
Hope someone would like to give me some tips to solve this error, thanks!

**Comment by bchatard** [comment]
Hi @lxy1992,

How did you install PyCharm? (JB Toolbox, Brew cask, by downloading it from JB website)
Which version of PyCharm did you use? (Community, Professional or Edu)

**Comment by lxy1992** [comment]
Hi, @bchatard 
Sorry for responding so slowly. I'm busying in working lately.
I install the **Professional version** by downloading D**MG package** from JB website. Then, for enabling the shell script function, I downloaded the **JB Tool Box**
Now, I have open the shell script function and installed this npm package successfully to the newest version. It still presents the same error message. Hope you may give me some help, thanks!

**Comment by bchatard** [comment]
Hi,
Why did you install PyCharm from .dmg and from toolbox?
In toolbox, did you see the script name, in PyCharm settings?

![image](https://user-images.githubusercontent.com/829364/58072686-c44ee780-7ba0-11e9-88f5-8b0bec5157c5.png)

**Comment by lxy1992** [comment]
Hi,
Yes, I saw it.

**Comment by lxy1992** [comment]
![5C5E58EA-0278-4FD4-8DB4-74570D0D719C](https://user-images.githubusercontent.com/6184994/59734367-cb424600-9283-11e9-8e48-c6d7884843e0.png)
