### ISSUE TITLE
I just updated the version, but it feels a lot slower than the previous PHP version. Is it normal?

### ISSUE THREAD

**Issue by cnlinjie** [bchatard/alfred-jetbrains#132]
**Check [Troubleshooting](/doc/troubleshooting.md) first**

**Describe the bug**
I just updated the version, but it feels a lot slower than the previous PHP version. Is it normal?

**To Reproduce**
idea ...

**Expected behavior**

**Screenshots**

| Q                         | A                                      |
| ------------------------- | -------------------------------------- |
| Workflow version          | _1.3.3_                                |
| OSX Version               | _10.14.5_                              |
| Alfred Version            | _ 4.0.9_                                  |
| JetBrains Product/Version | _PhpStorm / 2020.1_                    |
| Installation type         | _JB Toolbox_ |
| Node version              | _v12.16.2_ (`node --version`)            |
| NPM version               | _6.14.4_ (`npm --version`)              |

**Additional context**

**Comment by bchatard** [comment]
hi

I run some test,  and I did not notice performance issue

Without cache:
![image](https://user-images.githubusercontent.com/829364/80678704-c19c8800-8abb-11ea-9971-3a5766e450fd.png)

With cache:
![image](https://user-images.githubusercontent.com/829364/80678759-db3dcf80-8abb-11ea-9cc6-9e7ecb4240a1.png)


You can check this metrics when debug console is open in workflow configuration (last items)

**Comment by cnlinjie** [comment]
Sorry, because I went out for a holiday, I only see your reply now.
The time just tested out is:
```
		{
			"title": "Retrieve Product: 13ms",
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Clock.icns"
			}
		},
		{
			"title": "Retrieve Projects: 73ms",
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Clock.icns"
			}
		}
```
It's not very long, but it seems a bit slow compared to the previous one,
Maybe it ’s not your code, I ’ll record a video later.

**Comment by cnlinjie** [comment]
NPM Version :
https://cdn.reworking.fr.emallos.com/videonew-version-npm.mov

PHP Version:
https://cdn.reworking.fr.emallos.com/videoold-version-php.mov

**Comment by cnlinjie** [comment]
@bchatard  This is not a big problem. The performance may vary between different languages. I'm sorry for taking up your time.

**Comment by bchatard** [comment]
hi @cnlinjie 

thanks for your great feedback. 
Indeed there is a performance degradation in your videos, maybe related with the "bootstrap" of nodejs. I will take a look on this

**Comment by bchatard** [comment]
a little bit of 3 years later

should be better now
