### ISSUE TITLE
Add Android Studio Support

### ISSUE THREAD

**Issue by bchatard** [bchatard/alfred-jetbrains#14]
Q | A
--- | ---
Workflow version | _1.0.9_
OSX Version | _10.14.4_
Alfred Version | _3.8_
JetBrains Product/Version | _Android Studio / 2019.1_
Installation type | _all_

### Description
Add Android Studio support

**Comment by AlexeyKorshun** [comment]
do you plan to support Android studio?

**Comment by bchatard** [comment]
yes, it's planned but no real time to handle this point

I will try to work on it this week. 

Did you have some "tips" about Android Studio, which can help me to integrate it with the workflow?

**Comment by AlexeyKorshun** [comment]
oh sorry i don't have. I used previous version of this workflow and it was great.

**Comment by bchatard** [comment]
@AlexeyKorshun please, check release 1.2.0

**Comment by AlexeyKorshun** [comment]
@bchatard thx it work.
