### ISSUE TITLE
pstorm only show two projects

### ISSUE THREAD

**Issue by IvanG11** [bchatard/alfred-jetbrains#147]
**Describe the bug**
Alfred can't find all my projects, can only find two.

**Expected behavior**
Alfred list all my project.

**Screenshots**
Alfred
<img width="784" alt="alfred" src="https://user-images.githubusercontent.com/1247325/85035053-0c18b780-b183-11ea-92a0-da0aa6209502.png">

Toolbox
<img width="440" alt="Screen Shot 2020-06-18 at 16 46 02" src="https://user-images.githubusercontent.com/1247325/85035327-513ce980-b183-11ea-8177-7f856de61eaa.png">

| Q                         | A                                      |
| ------------------------- | -------------------------------------- |
| Workflow version          | _1.3.4_                                |
| OSX Version               | _10.15.5_                              |
| Alfred Version            | _4.0.9_                                  |
| JetBrains Product/Version | _PhpStorm / 2020.1_                    |
| Installation type         | _JB Toolbox_ |
| Node version              | _14.4.0_ (`node --version`)            |
| NPM version               | _6.14.4_ (`npm --version`)              |

**Additional context**
cat $(which phpstorm)
```
#!/bin/sh
# Generated by JetBrains Toolbox 1.17.7018 at 2020-06-18T16:45:16.003302

open -na "/Users/user/Library/Application Support/JetBrains/Toolbox/apps/PhpStorm/ch-0/201.7846.90/PhpStorm.app/Contents/MacOS/phpstorm" --args "$@"
```

**Comment by bchatard** [comment]
Can you flush the cash of this workflow and try again

**Comment by IvanG11** [comment]
Sorry I don't know what you mean by flush the cash, I have tried to delete the projects from phpstorm and reopen them but the same two projects keep showing up

**Comment by bchatard** [comment]
this workflow cache list of projects per default, when you create a new project you need to flush cache to see new project

https://github.com/bchatard/alfred-jetbrains#clean-projects-cache

**Comment by IvanG11** [comment]
today I restored the Phpstorm to defaults and now shows more projects, but if I open other projects and clean the workflow cache with jb doesn't appear the new projects in the workflow

**Comment by ahmeed83** [comment]
Same problem here. It doesn't show all the projects that I have. Is there a possibility to let is search on one folder that contains all the projects? 

By the way, I tried cat ~/Library/Preferences/IntelliJIdea2019.3/options/recentProjects.xml and I found projects which I have on my local machine but I also cant find with the plugin.

**Comment by IvanG11** [comment]
After updating PhpStorm to version 2020.2 and running the jb command to clear the cache. Now the workflow already shows me all the projects.
