### ISSUE TITLE
Error when using "idea" in alfred

### ISSUE THREAD

**Issue by tjosinga** [bchatard/alfred-jetbrains#15]
Q | A
--- | ---
Workflow version | _1.0.9_
OSX Version | _10.14.4_
Alfred Version | _3.8.1_
JetBrains Product/Version | _IntelliJ / 2019.1_
Installation type | _JB Toolbox_

### Description
In the terminal, the command-line `idea ./` works perfectly, but not when using Alfred. I get an "Unexpected token ..." error in Alfred, which I can copy:

```
/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:42
            ...product,
            ^^^
SyntaxError: Unexpected token ...
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:7:38)

-
JetBrains - Open Project - v3 1.0.9
Alfred 3.8.1
darwin x64 18.5.0
```

In another issue you requested the content of the idea file. In my case it is:
```
$> cat $(which idea)

#!/bin/sh
# Generated by JetBrains Toolbox 1.14.5179 at Mon Apr 15 16:37:15 2019

open -a "/Users/taco/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/191.6183.87/IntelliJ IDEA.app/Contents/MacOS/idea" "$@"
```

### Step to reproduce
Just by typing idea in Alfred.

**Comment by bchatard** [comment]
Hi @tjosinga 
which version of nodejs do you have?

**Comment by tjosinga** [comment]
Both v6.14.3 and v11.14.0. I have set the latter as default, but maybe the problem is that Alfred is not using the correct version?

**Comment by tjosinga** [comment]
```
$> nvm use system
Now using system version of node: v11.12.0 (npm v6.7.0)
```
The system version seems to be 11.12.

**Comment by bchatard** [comment]
ok, I'm not familiar with NVM.
Can you try to add the following line in the "idea script filter": `./node_modules/.bin/run-node --version
`

⚠️ Heavy GIF ⚠️ 
![Kapture 2019-04-16 at 10 57 09](https://user-images.githubusercontent.com/829364/56196131-8d803180-6036-11e9-8431-ad20b4d1e85b.gif)

**Comment by tjosinga** [comment]
Aaa, yes, Alfred uses v6.14.3.

So I tried installing a new system node.js version (without nvm), using the instructions on: https://solarianprogrammer.com/2016/04/29/how-to-upgrade-nodejs-mac-os-x/
That didn't do the trick, yet (also restarted Alfred), though I saw some differences (maybe I was too quick).

Then I noted that there is a new version 1.0.10, so I removed 1.0.9 and installed 1.0.10, and it worked.

**Comment by tjosinga** [comment]
So in short, when using NVM one may think he is using a recent version of node.js (based on the output in shell), but in fact, it may be an old version.

**Comment by bchatard** [comment]
o_O I did not change stuff on this in 1.0.10...

I know that Alfred doesn't export your path, but a "lighter one" maybe it's related. I use [Alfy](https://github.com/sindresorhus/alfy) under the hood, which handle this case (https://github.com/sindresorhus/alfy/issues/73#issuecomment-349260386)

**Comment by bchatard** [comment]
Hi @tjosinga,

I add a validation of node version at the begin of the process. It will be more easier to debug.

Thanks for your help

**Comment by tjosinga** [comment]
👍
