### ISSUE TITLE
After I upgraded from 1.3.4 to 1.4.0, I couldn't find any projects using wstorm. How to solve this problem?

### ISSUE THREAD

**Issue by eagleonefight** [bchatard/alfred-jetbrains#157]
**Check [Troubleshooting](/doc/troubleshooting.md) first**

**Describe the bug**
I couldn't find any projects using wstorm

**To Reproduce**

1. Use the wstorm command
2. and then display Open WebStorm Project
3. but no project directory can be found, and no project directory is displayed

**Expected behavior**

Expect alfred to appear in my project directory

**Screenshots**

first i start input:

![Image_20200828133211](https://user-images.githubusercontent.com/13845910/91524962-0eda1a80-e933-11ea-8893-8f519d660a80.png)

then something is searching :

![Image_20200828133536](https://user-images.githubusercontent.com/13845910/91525170-7a23ec80-e933-11ea-8346-1f59080ab65a.png)

then result nothing:

![Image_20200828110735](https://user-images.githubusercontent.com/13845910/91516699-b731b400-e91e-11ea-8168-421bc4851d06.png)

my webstorm table of Contents：

![Image_20200828134344](https://user-images.githubusercontent.com/13845910/91525624-852b4c80-e934-11ea-9f5e-bbd5fe3a2b71.png)

| Q                         | A                                      |
| ------------------------- | -------------------------------------- |
| Workflow version          | _1.4.0_                                |
| OSX Version               | _10.15.6_                              |
| Alfred Version            | _4.1.1_                                  |
| JetBrains Product/Version | _WebStorm / 2020.2_                    |
| Installation type         | _JB Toolbox_ |
| Node version              | _12.12.0_            |
| NPM version               | _6.14.0_               |

**Additional context**

**Comment by bchatard** [comment]
Please fill information about the issue (template) and try the troubleshoot guide too

**Comment by eagleonefight** [comment]
> Please fill information about the issue (template) and try the troubleshoot guide too

I have checked the https://github.com/doc/troubleshooting.md, I didn’t prompt any error, just that the project directory could not be found, the following is what I got by running cat $(which webstorm)

**#!/bin/sh
# Generated by JetBrains Toolbox 1.17.7391 at 2020-08-27T17:55:52.125552

open -na "/Users/eagle/Library/Application Support/JetBrains/Toolbox/apps/WebStorm/ch-0/202.6948.73/WebStorm.app/Contents/MacOS/webstorm" --args "$@"**

**Comment by MarcusNotheis** [comment]
I'm facing the same issue. For me it looks like there are some `node_module` missing?

> [12:05:15.819] Logging Started...
> [12:05:20.706] JetBrains - Open Project - v3[Script Filter] Queuing argument ''
> [12:05:21.067] JetBrains - Open Project - v3[Script Filter] Script with argv '' finished
> [12:05:21.069] STDERR: JetBrains - Open Project - v3[Script Filter] (node:2865) UnhandledPromiseRejectionWarning: /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/read-pkg-up/node_modules/parse-json/index.js:1
> Error: Cannot find module 'json-parse-better-errors'
> Require stack:
> - /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/read-pkg-up/node_modules/parse-json/index.js
> - /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/read-pkg-up/node_modules/read-pkg/index.js
> - /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/read-pkg-up/index.js
> - /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/alfy/lib/update-notification.js
> - /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/alfy/index.js
> - /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js
>     at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/read-pkg-up/node_modules/parse-json/index.js:3:18)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
> (node:2865) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:2865) UnhandledPromiseRejectionWarning: TypeError: updateNotification is not a function
>     at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/alfy/index.js:14:1
>     at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/alfy/index.js:166:3)
>     at Generator.next (<anonymous>)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
> (node:2865) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> (node:2865) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'get' of undefined
>     at Object.get (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:153:36)
>     at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:13:38
>     at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)
>     at Generator.next (<anonymous>)
> (node:2865) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

**Comment by bchatard** [comment]
hi,

sorry for late reply, I just try and everything works fine

**Comment by boyd91** [comment]
Same here, also complaining about missing `json-parse-better-errors`. My node version is 14

**Comment by bchatard** [comment]
can you provide the contact of `/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/read-pkg-up/node_modules/parse-json/package.json`?

thanks

**Comment by eagleonefight** [comment]
> can you provide the contact of `/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/read-pkg-up/node_modules/parse-json/package.json`?
> 
> thanks

{
  "_from": "parse-json@^5.0.0",
  "_id": "parse-json@5.1.0",
  "_inBundle": false,
  "_integrity": "sha1-+WCIzfJKj6qa6poAny2dlCyZlkY=",
  "_location": "/@bchatard/alfred-jetbrains/read-pkg-up/parse-json",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "parse-json@^5.0.0",
    "name": "parse-json",
    "escapedName": "parse-json",
    "rawSpec": "^5.0.0",
    "saveSpec": null,
    "fetchSpec": "^5.0.0"
  },
  "_requiredBy": [
    "/@bchatard/alfred-jetbrains/read-pkg-up/read-pkg"
  ],
  "_resolved": "https://registry.npm.taobao.org/parse-json/download/parse-json-5.1.0.tgz?cache=0&sync_timestamp=1598129230057&other_urls=https%3A%2F%2Fregistry.npm.taobao.org%2Fparse-json%2Fdownload%2Fparse-json-5.1.0.tgz",
  "_shasum": "f96088cdf24a8faa9aea9a009f2d9d942c999646",
  "_spec": "parse-json@^5.0.0",
  "_where": "/Users/eagle/.npm-global/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/read-pkg-up/node_modules/read-pkg",
  "author": {
    "name": "Sindre Sorhus",
    "email": "sindresorhus@gmail.com",
    "url": "https://sindresorhus.com"
  },
  "bugs": {
    "url": "https://github.com/sindresorhus/parse-json/issues"
  },
  "bundleDependencies": false,
  "dependencies": {
    "@babel/code-frame": "^7.0.0",
    "error-ex": "^1.3.1",
    "json-parse-even-better-errors": "^2.3.0",
    "lines-and-columns": "^1.1.6"
  },
  "deprecated": false,
  "description": "Parse JSON with more helpful errors",
  "devDependencies": {
    "ava": "^1.4.1",
    "nyc": "^14.1.1",
    "xo": "^0.24.0"
  },
  "engines": {
    "node": ">=8"
  },
  "files": [
    "index.js",
    "vendor"
  ],
  "funding": "https://github.com/sponsors/sindresorhus",
  "homepage": "https://github.com/sindresorhus/parse-json#readme",
  "keywords": [
    "parse",
    "json",
    "graceful",
    "error",
    "message",
    "humanize",
    "friendly",
    "helpful",
    "string"
  ],
  "license": "MIT",
  "name": "parse-json",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/sindresorhus/parse-json.git"
  },
  "scripts": {
    "test": "xo && nyc ava"
  },
  "version": "5.1.0"
}

**Comment by bchatard** [comment]
weird, same parse-json version but not the same dependencies...

```json
{
  "_from": "parse-json@^5.0.0",
  "_id": "parse-json@5.0.1",
  "_inBundle": false,
  "_integrity": "sha512-ztoZ4/DYeXQq4E21v169sC8qWINGpcosGv9XhTDvg9/hWvx/zrFkc9BiWxR58OJLHGk28j5BL0SDLeV2WmFZlQ==",
  "_location": "/@bchatard/alfred-jetbrains/read-pkg-up/parse-json",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "parse-json@^5.0.0",
    "name": "parse-json",
    "escapedName": "parse-json",
    "rawSpec": "^5.0.0",
    "saveSpec": null,
    "fetchSpec": "^5.0.0"
  },
  "_requiredBy": [
    "/@bchatard/alfred-jetbrains/read-pkg-up/read-pkg"
  ],
  "_resolved": "https://registry.npmjs.org/parse-json/-/parse-json-5.0.1.tgz",
  "_shasum": "7cfe35c1ccd641bce3981467e6c2ece61b3b3878",
  "_spec": "parse-json@^5.0.0",
  "_where": "/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/read-pkg-up/node_modules/read-pkg",
  "author": {
    "name": "Sindre Sorhus",
    "email": "sindresorhus@gmail.com",
    "url": "https://sindresorhus.com"
  },
  "bugs": {
    "url": "https://github.com/sindresorhus/parse-json/issues"
  },
  "bundleDependencies": false,
  "dependencies": {
    "@babel/code-frame": "^7.0.0",
    "error-ex": "^1.3.1",
    "json-parse-better-errors": "^1.0.1",
    "lines-and-columns": "^1.1.6"
  },
...
```

Can you try to re-install this workflow? (remove + install)

**Comment by boyd91** [comment]
I tried removing and fresh installing it yesterday, made no difference. Here's the contents of mine:

```
{
  "_from": "parse-json@^5.0.0",
  "_id": "parse-json@5.1.0",
  "_inBundle": false,
  "_integrity": "sha512-+mi/lmVVNKFNVyLXV31ERiy2CY5E1/F6QtJFEzoChPRwwngMNXRDQ9GJ5WdE2Z2P4AujsOi0/+2qHID68KwfIQ==",
  "_location": "/@bchatard/alfred-jetbrains/read-pkg-up/parse-json",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "parse-json@^5.0.0",
    "name": "parse-json",
    "escapedName": "parse-json",
    "rawSpec": "^5.0.0",
    "saveSpec": null,
    "fetchSpec": "^5.0.0"
  },
  "_requiredBy": [
    "/@bchatard/alfred-jetbrains/read-pkg-up/read-pkg"
  ],
  "_resolved": "https://registry.npmjs.org/parse-json/-/parse-json-5.1.0.tgz",
  "_shasum": "f96088cdf24a8faa9aea9a009f2d9d942c999646",
  "_spec": "parse-json@^5.0.0",
  "_where": "/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/read-pkg-up/node_modules/read-pkg",
  "author": {
    "name": "Sindre Sorhus",
    "email": "sindresorhus@gmail.com",
    "url": "https://sindresorhus.com"
  },
  "bugs": {
    "url": "https://github.com/sindresorhus/parse-json/issues"
  },
  "bundleDependencies": false,
  "dependencies": {
    "@babel/code-frame": "^7.0.0",
    "error-ex": "^1.3.1",
    "json-parse-even-better-errors": "^2.3.0",
    "lines-and-columns": "^1.1.6"
  },
  "deprecated": false,
  "description": "Parse JSON with more helpful errors",
  "devDependencies": {
    "ava": "^1.4.1",
    "nyc": "^14.1.1",
    "xo": "^0.24.0"
  },
  "engines": {
    "node": ">=8"
  },
  "files": [
    "index.js",
    "vendor"
  ],
  "funding": "https://github.com/sponsors/sindresorhus",
  "homepage": "https://github.com/sindresorhus/parse-json#readme",
  "keywords": [
    "parse",
    "json",
    "graceful",
    "error",
    "message",
    "humanize",
    "friendly",
    "helpful",
    "string"
  ],
  "license": "MIT",
  "name": "parse-json",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/sindresorhus/parse-json.git"
  },
  "scripts": {
    "test": "xo && nyc ava"
  },
  "version": "5.1.0"
}
```

**Comment by eagleonefight** [comment]
> weird, same parse-json version but not the same dependencies...
> 
> ```json
> {
>   "_from": "parse-json@^5.0.0",
>   "_id": "parse-json@5.0.1",
>   "_inBundle": false,
>   "_integrity": "sha512-ztoZ4/DYeXQq4E21v169sC8qWINGpcosGv9XhTDvg9/hWvx/zrFkc9BiWxR58OJLHGk28j5BL0SDLeV2WmFZlQ==",
>   "_location": "/@bchatard/alfred-jetbrains/read-pkg-up/parse-json",
>   "_phantomChildren": {},
>   "_requested": {
>     "type": "range",
>     "registry": true,
>     "raw": "parse-json@^5.0.0",
>     "name": "parse-json",
>     "escapedName": "parse-json",
>     "rawSpec": "^5.0.0",
>     "saveSpec": null,
>     "fetchSpec": "^5.0.0"
>   },
>   "_requiredBy": [
>     "/@bchatard/alfred-jetbrains/read-pkg-up/read-pkg"
>   ],
>   "_resolved": "https://registry.npmjs.org/parse-json/-/parse-json-5.0.1.tgz",
>   "_shasum": "7cfe35c1ccd641bce3981467e6c2ece61b3b3878",
>   "_spec": "parse-json@^5.0.0",
>   "_where": "/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/read-pkg-up/node_modules/read-pkg",
>   "author": {
>     "name": "Sindre Sorhus",
>     "email": "sindresorhus@gmail.com",
>     "url": "https://sindresorhus.com"
>   },
>   "bugs": {
>     "url": "https://github.com/sindresorhus/parse-json/issues"
>   },
>   "bundleDependencies": false,
>   "dependencies": {
>     "@babel/code-frame": "^7.0.0",
>     "error-ex": "^1.3.1",
>     "json-parse-better-errors": "^1.0.1",
>     "lines-and-columns": "^1.1.6"
>   },
> ...
> ```
> 
> Can you try to re-install this workflow? (remove + install)

I found the reason. I used npm uninstall -g @bchatard/alfred-jetbrains, but there are still residual directories in the global directory. **I manually delete the directory and install it again**. This plugin is just fine. This is a very useful plugin👏

**Comment by bchatard** [comment]
Nice catch! node js can be really really weird...

I will update the troubleshooting guide for this case.

Thanks again!

**Comment by boyd91** [comment]
Can confirm this works here as well, thanks for the help!
