### ISSUE TITLE
Wrong PyCharm path

### ISSUE THREAD

**Issue by carlba** [bchatard/alfred-jetbrains#16]
Q | A
--- | ---
Workflow version | _1.0.0_
OSX Version | _10.14.4_
Alfred Version | _3.8_
JetBrains Product/Version | _PyCharm / 2019.1_
Installation type | _Toolbox_

### Description

In src/products.json: 

```json
  "PyCharmPro": {
    "preferences": "PyCharm",
    "bin": "pycharm"
  },
```
Should probably be replaced with
```json
  "PyCharmPro": {
    "preferences": "PyCharm",
    "bin": "charm"
  },
```

Since that is what JetBrains toolbox actually generates.

**Comment by bchatard** [comment]
Hi @carlba,

With the toolbox I have `pycharm` as default bin name (fresh install a new mac).
Did you change the `bin` name in a previous version?

**Comment by carlba** [comment]
How do you change the bin name. I might have done it a long time a go.

Best Regards Carl Bäckström

**Comment by bchatard** [comment]
You can change the `bin` name in the toolbox (in product settings) or in the workflow (see. [doc](https://github.com/bchatard/alfred-jetbrains/blob/master/doc/customisation/product.md)
