### ISSUE TITLE
File action fails when project folder name has space in it.

### ISSUE THREAD

**Issue by abbasegbeyemi** [bchatard/alfred-jetbrains#171]
**Check [Troubleshooting](/doc/troubleshooting.md) first**

**Describe the bug**
Opening a project folder with the file action feature fails and does not open PyCharm. Screen shots are included. It appears not to be parsing filenames with spaces correctly. 

**To Reproduce**

1. Create a folder with a space in the folder name eg "Test Project"
2. Run Alfred, navigate to the folder and select the Open in PyCharm file action. 
3. If PyCharm is already running, the running window shows the error saying it cant open the folder. 
4. If PyCharm is not running, it freezes and you have to force quit PyCharm. The notification then shows the error. 

**Debug Output**
```
[18:54:07.135] JetBrains - Open Project - v3[File Action] Processing complete
[18:54:07.167] JetBrains - Open Project - v3[File Action] Passing output '/Users/abbasegbeyemi/Desktop/Test Project' to Run Script
[18:54:07.786] JetBrains - Open Project - v3[Run Script] Processing complete
[18:54:07.803] JetBrains - Open Project - v3[Run Script] Passing output '{
  uid: 'Test Project',
  title: 'Test Project',
  match: 'Test Project',
  subtitle: '/Users/abbasegbeyemi/Desktop/Test Project',
  arg: '/Users/abbasegbeyemi/Desktop/Test Project',
  autocomplete: 'Test Project',
  text: {
    copy: '/Users/abbasegbeyemi/Desktop/Test Project',
    largetype: 'Test Project'
  },
  icon: { path: '/Applications/PyCharm.app', type: 'fileicon' },
  variables: {
    jb_project_name: 'Test Project',
    jb_bin: '/usr/local/bin/charm',
    jb_search_basename: 'Test Project'
  }
}
' to Run Script
[18:55:06.755] JetBrains - Open Project - v3[Run Script] Processing complete
[18:55:06.763] JetBrains - Open Project - v3[Run Script] Passing output 'Cannot find file '/Users/abbasegbeyemi/Desktop/Test'
  Test  Project
' to Post Notification
```

Things seem to be going wrong in the second script. 

**Expected behavior**
Selecting open in PyCharm should open the file in PyCharm as long as the file has a system permitted filename.

**Screenshots**
<img width="365" alt="Screenshot 2020-11-20 at 18 55 21" src="https://user-images.githubusercontent.com/28359481/99839457-a16d0d00-2b62-11eb-8487-c8ca58a227fa.png">
<img width="827" alt="Screenshot 2020-11-20 at 19 01 55" src="https://user-images.githubusercontent.com/28359481/99839613-ed1fb680-2b62-11eb-9821-937782ad036f.png">
<img width="709" alt="Screenshot 2020-11-20 at 19 01 35" src="https://user-images.githubusercontent.com/28359481/99839619-ef821080-2b62-11eb-986e-d044a3670e5c.png">

| Q                         | A                                      |
| ------------------------- | -------------------------------------- |
| Workflow version          | _1.4.1_                                |
| OSX Version               | _11.0.1_                              |
| Alfred Version            | _4.2.1_                                  |
| JetBrains Product/Version | _PyCharm / 2020.2_                    |
| Installation type         | _classic .dmg |
| Node version              | _14.8.0_ (`node --version`)            |
| NPM version               | _6.14.8_ (`npm --version`)              |

**Additional context**
It works perfectly fine if the folder name does not have a space in it. So maybe this bug is not that big of a deal. 

I'm not very familiar with sh, and I have just installed Alfred for the first time today. But I will take a crack at fixing the issue and maybe submit a pull request if I can.

**Comment by bchatard** [comment]
please bump to version 1.4.3 and enjoy your work ;)

thanks again for your contribution
