### ISSUE TITLE
When project groups are defined, under 2020.3 no projects can be retrieved

### ISSUE THREAD

**Issue by rymek** [bchatard/alfred-jetbrains#177]
**Describe the bug**
When project groups are defined, under 2020.3 no projects can be retrieved

**To Reproduce**

1. Create project group inside IntelliJ
2. Add project to group
3. Exit IntelliJ
4. Clean project cache (jb clean cache)
5. try to find projects using alfred
6. no projects found

**Expected behavior**
Projects retrieved correctly.

I've created PR to fix this issue here:
https://github.com/bchatard/alfred-jetbrains/pull/176

**Comment by zczhangchun** [comment]
me too

**Comment by bchatard** [comment]
please bump to version 1.4.4 (and thanks for your contribution @rymek !)
