### ISSUE TITLE
Can't find application path for IntelliJIdea. (2020.3)

### ISSUE THREAD

**Issue by sungjk** [bchatard/alfred-jetbrains#184]
Q | A
--- | ---
Workflow version | 1.4.4
OSX Version | 10.15.7
Alfred Version | 4.3
JetBrains Product/Version | IntelliJIdea / 2020.3
Installation type | JB Toolbox_

### Description
I updated intellij to 2020.3(latest) and got this message. Previously, I solved it by reinstalling like below, but this time I couldn't.

```
$ rm -rf /usr/local/lib/node_modules/@bchatard
$ npm uninstall -g @bchatard/alfred-jetbrains
$ npm install -g @bchatard/alfred-jetbrains
```

And this message appears the same on my other MacBook.

<img width="594" alt="Screen Shot 2020-12-20 at 19 52 17" src="https://user-images.githubusercontent.com/9454446/102711410-df458880-42fc-11eb-8b0b-caaf00b1cf93.png">

### Errors
```
Error: Can't find application path for IntelliJIdea.
    at getApplicationPath (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:148:9)
    at Object.get (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:158:31)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:13:38
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054
    at Generator.next (<anonymous>)
    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)
    at kl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)
    at Object.u (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)

JetBrains - Open Project - v3 1.4.4
Alfred 4.3
darwin 19.6.0
```

### screenshot
- Toolbox App Settings
- ![image](https://user-images.githubusercontent.com/9454446/102711770-87f4e780-42ff-11eb-9439-a29a74c5b31d.png)
- IntelliJ IDEA Ultimate Settings
- ![image](https://user-images.githubusercontent.com/9454446/102711785-99d68a80-42ff-11eb-8b9a-57c014631d65.png)

### print idea
```
$ which idea
/usr/local/bin/idea
```

```
$ cat $(which idea)
#!/bin/sh
#Generated by JetBrains Toolbox 1.19.7784 at 2020-12-20T19:54:49.634126

declare -a ideargs=()
declare -- wait=""

for o in "$@"; do
  if [[ "$o" = "--wait" || "$o" = "-w" ]]; then
    wait="-W"
    o="--wait"
  fi
  if [[ "$o" =~ " " ]]; then
    ideargs+=("\"$o\"")
  else
    ideargs+=("$o")
  fi
done

open -na "/Users/jeremy/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/203.5981.155/IntelliJ IDEA.app/Contents/MacOS/idea" $wait --args "${ideargs[@]}"
```

Thanks!

**Comment by adian** [comment]
I have the same problem :/

**Comment by rymek** [comment]
You have to change product.js line 128 from:
`  const pattern = new RegExp('open -(n)?a "(.*)"( --args)? "\\$@"');`
to
`  const pattern = new RegExp('open -(n)?a "(.*)"( --args)?');`

not sure how it affects older versions thought (older toolbox/jetbrains products versions)

**Comment by sungjk** [comment]
@rymek  Thanks for the rapid response! That fixed it. 

@bchatard Could this be considered a bug?

**Comment by bchatard** [comment]
@sungjk please don't close the issue if you want a fix. Check 1.5.0 that fix the issue

related to #186
