### ISSUE TITLE
"Can't find application path for..." with shell scripts from Toolbox 1.19.7784

### ISSUE THREAD

**Issue by marcorieser** [bchatard/alfred-jetbrains#185]
**Describe the bug**
The latest Toolbox changes the structure of the shell script from
`open -na "/PATH/TO/APPS/DIRECTORY/PhpStorm.app/Contents/MacOS/phpstorm" --args "$@"`
to
`open -na "/PATH/TO/APPS/DIRECTORY/PhpStorm.app/Contents/MacOS/phpstorm" $wait --args "${ideargs[@]}"`
Because the current regular expression doesn't match with the new pattern, the path can not be found.

**To Reproduce**
- Update the Toolbox
- Update the workflow
- Restart Mac
- Open Alfred
- Type 'pstorm '
- See the error

**Expected behavior**
A list of the last opened projects from PhpStorm.

| Q                         | A                                      |
| ------------------------- | -------------------------------------- |
| Workflow version          | _1.4.4_                                |
| OSX Version               | _10.15.7_                              |
| Alfred Version            | _4.3 (1205)_                                  |
| JetBrains Product/Version | _PhpStorm / 2020.3_                    |
| Toolbox Version | _1.19.7784_                    |
| Installation type         | _JB Toolbox_ |
| Node version              | _14.3.0_ (`node --version`)            |
| NPM version               | _6.14.10_ (`npm --version`)              |

**Comment by cameronsstone** [comment]
Thanks - this affected me, too. I've made a different modification locally to fix it - I just removed the args part:
removed:
```
  const pattern = new RegExp('open -(n)?a "(.*)"( --args)? "\\$@"');
```
replaced with:
```
  const pattern = new RegExp('open -(n)?a "(.*)"( --args)?');
```

This should work with the latest toolbox, and also the previous versions this regex supported. :-)

**Comment by marcorieser** [comment]
I have no old shell scripts available to test if my solution works with them. I just found an old shell script in another issue and made sure my regex catches this and my new shell shript. Also did not realy go trough the match logic below the regex to see which groups / parts are needed, just made sure the groups are the same.

**Comment by cameronsstone** [comment]
Thanks @bchatard . Pulled the new code and everything is working perfectly. Cheers!

**Comment by cameronsstone** [comment]
Oh, and thanks, obviously, to @marcorieser , too!
