### ISSUE TITLE
upgraded to idea2020.3, the workflow was unavailable and there was an error in Alfred

### ISSUE THREAD

**Issue by kqixiang945** [bchatard/alfred-jetbrains#188]
**Check [Troubleshooting](/doc/troubleshooting.md) first**

**Describe the bug**
When I enter "ide" in the input box of alfred, there is a workflow prompt. When I enter "idea", there is no prompt, and see the error of the workflow in alfred as follows.

**Expected behavior**
When I use the previous version of the previous IDEA, this workflow still normal without any problems

**Screenshots**
![github](https://user-images.githubusercontent.com/14861321/103047563-df78a900-45c6-11eb-8eab-6695fb0cadaa.jpg)

![Xnip2020-12-24_09-03-51](https://user-images.githubusercontent.com/14861321/103047598-fc14e100-45c6-11eb-848d-195f5682efa8.jpg)
![Xnip2020-12-24_09-04-44](https://user-images.githubusercontent.com/14861321/103047635-1949af80-45c7-11eb-99ce-aaedc6fc21e0.jpg)

| Q                         | A                                      |
| ------------------------- | -------------------------------------- |
| Workflow version          | _1.5.0_                                |
| OSX Version               | _10.15.7_                              |
| Alfred Version            | _4.3_                                  |
| JetBrains Product/Version | IDEA Ultimate / 2020.3_                    |
| Installation type         | _classic .dmg  |
| Node version              | _12.13.1_ (`node --version`)            |
| NPM version               | _7.0.14_ (`npm --version`)              |

**Additional context**
When I enter "ide" in the input box of alfred, there is a workflow prompt. When I enter "idea", there is no prompt, and see the error of the workflow in alfred as follows:
```
[08:51:07.035] Logging Started...
[08:51:10.675] JetBrains - Open Project - v3[Script Filter] Queuing argument ''
[08:51:11.031] JetBrains - Open Project - v3[Script Filter] Script with argv '' finished
[08:51:11.034] STDERR: JetBrains - Open Project - v3[Script Filter] (node:8866) UnhandledPromiseRejectionWarning: /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/read-pkg-up/node_modules/parse-json/index.js:1
Error: Cannot find module 'json-parse-better-errors'
Require stack:
- /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/read-pkg-up/node_modules/parse-json/index.js
- /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/read-pkg-up/node_modules/read-pkg/index.js
- /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/read-pkg-up/index.js
- /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/alfy/lib/update-notification.js
- /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/alfy/index.js
- /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/read-pkg-up/node_modules/parse-json/index.js:3:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
(node:8866) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8866) UnhandledPromiseRejectionWarning: TypeError: updateNotification is not a function
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/alfy/index.js:14:1
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/alfy/index.js:166:3)
    at Generator.next (<anonymous>)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
(node:8866) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8866) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'get' of undefined
    at Object.get (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:154:36)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:13:38
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:60:3)
    at Generator.next (<anonymous>)
(node:8866) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```
Hope to get your reply, thanks!

**Comment by siripornpp** [comment]
I'm having the same problem.

**Comment by kqixiang945** [comment]
From the content of the error report:
It means I did not install the `json-parse-better-errors` module of node, and then I manually installed the `json-parse-better-errors module`, and the `parse json` module 
uses the command: 
`npm install --save json-parse -better-errors` and `npm install parse-json`, but there are still the above errors.
![Xnip2020-12-24_11-19-15](https://user-images.githubusercontent.com/14861321/103057226-e4932380-45d9-11eb-8a2c-47c4abcd3d0a.jpg)

Hope @bchatard can help me.

**Comment by bchatard** [comment]
Please check https://github.com/bchatard/alfred-jetbrains/issues/110#issuecomment-745465985

**Comment by kqixiang945** [comment]
> Please check [#110 (comment)](https://github.com/bchatard/alfred-jetbrains/issues/110#issuecomment-745465985)

@bchatard  It's great!!! everything is fine!! 😁😁😁😁  @siripornpp please have a try!!

**Comment by kqixiang945** [comment]
@bchatard helped me , thanks a lot...
