### ISSUE TITLE
Enhance flush cache mechanism 

### ISSUE THREAD

**Issue by bchatard** [bchatard/alfred-jetbrains#2]
Allow to flush cache for an app (product or project)

**Comment by jornetsimon** [comment]
I noticed projects from the splash screen list that have been deleted from disk throw an error. Is this issue related?

**Comment by bchatard** [comment]
@jornetsimon sorry I don't fully understand the issue. The error is thrown is the workflow? If yes can you provide more information in a separate issue?
Thanks

**Comment by jornetsimon** [comment]
Can't reproduce the issue anymore. Consider it fix with latest patches.
