### ISSUE TITLE
PHPStorm uses the wrong environment variables when opened via Alfred workflow

### ISSUE THREAD

**Issue by sebastiaanluca** [bchatard/alfred-jetbrains#226]
**Describe the bug**
When searching for a project and opening it via the Alfred workflow, PHPStorm doesn't initialize using the terminal's default profile, but uses a custom one (or the system's default?). I believe this happens because the PWD/working directory is set to alfred-jetbrains' root dir, but it might be something else.

This causes several breaking issues, from default environment variables not being set to commands not working when running tests because the $PATH variable doesn't include the Homebrew directory. My initial issue was that, when running tests, it couldn't find the `mysql` command.

**To Reproduce**

1. Install the workflow
2. Search for a project
3. Open the project via Alfred
4. Echo an environment variable (e.g. `getenv('PATH')`) or run a non-system command (like one installed via Homebrew), either via the PHPStorm terminal or via code (`exec` or Symfony's `Process`).

**Expected behavior**
The Alfred workflow initializes all default terminal/iTerm settings. There's no issue when opening PHPStorm the regular way.

**Screenshots**
![Screenshot 2021-07-13 at 12 07 41](https://user-images.githubusercontent.com/711940/125434758-27e51dcb-4106-401a-a16f-e443c9ea8b5e.jpg)

| Q                         | A                                      |
| ------------------------- | -------------------------------------- |
| Workflow version          | 1.5.0                                |
| OSX Version               | 11.4                              |
| Alfred Version            | 4.3.4                                  |
| JetBrains Product/Version | PhpStorm / 2021.1.4                    |
| Installation type         | classic .dmg / Cask |
| Node version              | v16.3.0            |
| NPM version               | 7.15.1              |

**Comment by bchatard** [comment]
hi @sebastiaanluca,

I can't reproduce your issue (fresh macOS install, fresh Node/NPM - global, no nvm, fresh workflow)
How did you get the screenshot?

**Comment by sebastiaanluca** [comment]
Preferences > Terminal > Environment Variables (click the `$` dollar sign).

**Comment by bchatard** [comment]
on my side `PATH` is set correctly on PhpStorm (and others product). Maybe related to nvm. Can you try with a global node version?

**Comment by shilomagen** [comment]
Also reproduced on my end on IntelliJ. trying also to investigate to understand.

**Comment by bchatard** [comment]
@sebastiaanluca maybe it's related to nvm? did you have the ability to check without nvm?

**Comment by shilomagen** [comment]
I don't think it's related to nvm, I have issues with bazel env

**Comment by bchatard** [comment]
maybe something related to "node env managers". 
I use global node version, without this issue

**Comment by jdanino** [comment]
Running into the exact same problem where the system variables are different when opening a project from the Alfred workflow. I don't know how these environment variables are set from but the PATH is not the one I have set myself.. Not using any env managers..

**Comment by lvliangxiong** [comment]
> 

Hello jdanino, would you mind making a more detailed description of how you solve this problem, like where did you put the `source ~/.zshrc` command? Thank you!

**Comment by lvliangxiong** [comment]
> Running into the exact same problem where the system variables are different when opening a project from the Alfred workflow. I don't know how these environment variables are set from but the PATH is not the one I have set myself.. Not using any env managers..
> 
> edit:
> 
> Ok, so turns out that this is an Alfred thing: https://www.alfredapp.com/help/workflows/advanced/understanding-scripting-environment/
> 
> I fixed it by sourcing my .zshrc file before launching phpstorm

To supplement, this is where you should put your `source ~/.zshrc` command. 

<img width="749" alt="image" src="https://user-images.githubusercontent.com/25689191/145664517-7c753db4-a707-4bf4-a15b-809b180b52b7.png">

<img width="323" alt="image" src="https://user-images.githubusercontent.com/25689191/145664561-42a52709-b154-41e9-963f-e4188a9be3b5.png">

**Comment by bchatard** [comment]
Thanks, I commit your fix, release will arrive soon
