### ISSUE TITLE
Can't find workflow in alfred with node installed by nvm

### ISSUE THREAD

**Issue by urzz** [bchatard/alfred-jetbrains#229]
**Describe the bug**

I installed the node by nvm. And it's `node_modules` path not in `/usr/local/lib/node_modules`. So, when i done the installation `npm install -g @bchatard/alfred-jetbrains`, I can't find the workflow in the alfred.

After link the path, i can find and use the workflow.

```shell
# NODE_MODULE_PATH is the node_modules path for node installed by nvm
sudo ln -s NODE_MODULE_PATH /usr/local/lib/node_modules
```

| Q                         | A                                      |
| ------------------------- | -------------------------------------- |
| Workflow version          | _1.6.0_                                |
| OSX Version               | _11.4_                              |
| Alfred Version            | _4.5.1_                                  |
| JetBrains Product/Version | _Idea / 2021.2_                    |
| Installation type         | _JB Toolbox_ |
| Node version              | _v14.17.5_ (`node --version`)            |
| NPM version               | _6.14.14_ (`npm --version`)              |

**Comment by bchatard** [comment]
hi @urzz 

did you have any error on installation step?

**Comment by urzz** [comment]
@bchatard no, the problem seems to be trigger alfy-init failed, because last time i don't see any msg like `alfy-init`.
I tried remove the link and reinstall it, it succeed, and the problem can't be reappeared.
I think this issue can be closed, thx!
