### ISSUE TITLE
Links cannot be clearly identified

### ISSUE THREAD

**Issue by whimthen** [bchatard/alfred-jetbrains#23]
This theme is awesome👍
However, there is a problem:
Related links can modify the style, such as underline, color, etc.
There are contrast screenshots for reference here.
- gitark theme
![gitark_theme](https://ws1.sinaimg.cn/large/005LBZxugy1g3r8a3e8spj31cs0ugjvt.jpg)
- github theme
![github_theme](https://ws1.sinaimg.cn/large/005LBZxugy1g3r8a3er4lj31cw0u043f.jpg)

**Comment by bchatard** [comment]
Sorry I don't understand the issue, it's a simple markdown file without styles. 
Seems more related with your theme

**Comment by whimthen** [comment]
Ok, I mean, the links on the page are not easy to find, and there is no difference between ordinary texts, only when the mouse is put up, you can add a certain style to the links to distinguish them.

**Comment by bchatard** [comment]
As mentioned in my previous comment it's a markdown file, there is no style in. 
It's related to the theme gitark not this repo (check other repo too)
