### ISSUE TITLE
No projects listed

### ISSUE THREAD

**Issue by Glennmen** [bchatard/alfred-jetbrains#232]
**Describe the bug**
After updating to the latest version (v1.7.0) the projects are not listed anymore.

**To Reproduce**

1. Go to Alfred
2. Type `studio`
3. No projects listed

**Expected behavior**
A list of my Android Studio projects to be shown.

**Screenshots**

| Q                         | A                                      |
| ------------------------- | -------------------------------------- |
| Workflow version          | _1.7.0_                                |
| OSX Version               | _11.6_                              |
| Alfred Version            | _4.6.1_                                  |
| JetBrains Product/Version | _Android Studio / 2020.3.1 Patch 3_                    |
| Installation type         | _Homebrew_ |
| Node version              | _16.13.1_             |
| NPM version               | _8.1.2_              |

**Additional context**
Error message from Alfred debug logs:
```
[16:45:03.042] Logging Started...
[16:45:07.299] JetBrains - Open Project - v3[Script Filter] Queuing argument ''
[16:45:07.814] JetBrains - Open Project - v3[Script Filter] Script with argv '' finished
[16:45:07.817] ERROR: JetBrains - Open Project - v3[Script Filter] Code 1: /Users/glenncarremans/.nvm/versions/node/v16.13.1/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:1
(function (exports, require, module, __filename, __dirname) { import alfy from "alfy";
                                                                     ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    ```

**Comment by bchatard** [comment]
hi @Glennmen ,

try to remove / install, because it's seems to be an issue with dependencies installation

https://github.com/bchatard/alfred-jetbrains/blob/main/doc/troubleshooting.md#weird

**Comment by Glennmen** [comment]
@bchatard Thanks for the quick reply.
I tried it but still the same error.

**Comment by Glennmen** [comment]
@bchatard That line isn't being outputted to the debug log. 
It is the correct file because if I commented the alfy import line it gives an error for the next import line.

**Comment by Glennmen** [comment]
@bchatard Have you tried this workflow on Node v16? Because it seems you are currently testing it on node v14

**Comment by bchatard** [comment]
<img width="378" alt="CleanShot 2021-12-06 at 17 32 51@2x" src="https://user-images.githubusercontent.com/829364/144884797-3d93a88e-02fe-4e04-bb34-783af9e2af16.png">
 works on node 16 (and also 17)

the error is about a syntax issue (switch from `require` to `import`), but your node version support this syntax

Can you bump your node version or use a global version (without nvm)?

**Comment by Glennmen** [comment]
@bchatard I tried node 14 and 17 now but these also don't work, same error.
I have been using this workflow for over a year now I think and only recently after updating I am having this issue.

**Comment by bchatard** [comment]
ok, since I can't reproduce the issue, I can't help more on this.
Can you downgrade to v1.6.0, because 1.7.0 doesn't add features or bug fix

**Comment by Glennmen** [comment]
I have been on holiday for a couple of weeks and this week I noticed that the workflow works again 🤷🏼‍♂️
I don't think I changed anything. 
It is v1.7.0 and running node 17.

So I guess this ticket can be closed.

**Comment by xue2lang** [comment]
I meet the same problem (i use idea)，does has any solution for this ?

**Comment by xue2lang** [comment]
> I meet the same problem (i use idea)，does has any solution for this ?

both 1.7.0 and 1.7.1 have this problem , so i downgrade to 1.6.0 ,now it works ok，you can try it @Glennmen

**Comment by Glennmen** [comment]
> both 1.7.0 and 1.7.1 have this problem , so i downgrade to 1.6.0 ,now it works ok，you can try it @Glennmen

Hi, my problem is already solved but don't ask me how 😅 (https://github.com/bchatard/alfred-jetbrains/issues/232#issuecomment-1012005957) 
I am using version 1.7.0 currently.

**Comment by czende** [comment]
> > I meet the same problem (i use idea)，does has any solution for this ?
> 
> both 1.7.0 and 1.7.1 have this problem , so i downgrade to 1.6.0 ,now it works ok，you can try it @Glennmen

I can confirm that this solution solved the problem. I had the same error as described in the first post.
