### ISSUE TITLE
Feature Request: Allow setting custom bin name

### ISSUE THREAD

**Issue by LordZardeck** [bchatard/alfred-jetbrains#238]
Currently I use `wstorm` as my bin name for WebStorm, but "webstorm" is hard-coded in `products.js`. It would be nice if in the alfred workflow we could define a custom bin name for each product. I've manually edited the `products.js` file for now, but i'll lose that change on any update.

**Comment by bchatard** [comment]
Like this https://github.com/bchatard/alfred-jetbrains/blob/main/doc/customisation/bin.md ?

**Comment by LordZardeck** [comment]
Yup that's my bad, I completely missed the documentation on that. Thanks for pointing it out!
