### ISSUE TITLE
Studio list of projects doesn't updates

### ISSUE THREAD

**Issue by AlexeyKorshun** [bchatard/alfred-jetbrains#241]
Studio list of projects doesn't updates in workflow. I removed 7 of 8 projects, but it still appears in workflow list. This projects doesn't shown in recent projects in AS too.

| Q                         | A                                      |
| ------------------------- | -------------------------------------- |
| Workflow version          | _1.7.1_                                |
| OSX Version               | _12.2_                              |
| Alfred Version            | _4.6.2_                                  |
| JetBrains Product/Version | Android Studio Bumblebee 2021.1.1 Build #AI-211.7628.21.2111.8092744  |
| Installation type         | _classic .dmg_ |
| Node version              | _17.4.0_            |
| NPM version               | _8.3.1_              |

**Comment by bchatard** [comment]
Hi,

Project's list is cached. Did you try to flush cache?

**Comment by AlexeyKorshun** [comment]
how can I do this?

**Comment by bchatard** [comment]
https://github.com/bchatard/alfred-jetbrains#clean-projects-cache

**Comment by AlexeyKorshun** [comment]
I did it, but new projects didn't appears

**Comment by bchatard** [comment]
Did you completely close Studio app?

otherwise check the content of this file: `~/Library/Application\ Support/JetBrains/GoLand2021.3/options/recentProjects.xml` (adapt path to Studio product). 

and if possible provide it, so I can check what's happen

**Comment by AlexeyKorshun** [comment]
I found an error, script try to use old version path

````
Error: Can't find 'options' XML in /Users/alekseikorshun/Library/Application Support/Google/AndroidStudio4.2
    at getProjectPaths (file:///usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project/paths.js:132:9)
    at getItems (file:///usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project.js:44:19)
    at file:///usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:21:15
    at async Promise.all (index 0)
```

-
JetBrains - Open Project - v3 1.7.1
Alfred 4.6.2
darwin 21.3.0`

but current is  ~/Library/Application Support/Google/AndroidStudio2021.1/options

**Comment by AlexeyKorshun** [comment]
invalidate projects and product cache didn't help

**Comment by bchatard** [comment]
I just install latest Studio app, create a dummy app, close Studio, try to open via worklfow

<img width="814" alt="CleanShot 2022-01-31 at 09 59 57@2x" src="https://user-images.githubusercontent.com/829364/151765398-0be7f3f8-7334-4050-ae2b-d676d353614c.png">

**Comment by AlexeyKorshun** [comment]
it was maybe a problem via updates. try to fix it by self

**Comment by bchatard** [comment]
can you try to delete this folder: `/Users/alekseikorshun/Library/Application Support/Google/AndroidStudio4.2` (backup it  just in case)

I thinks I see the problem here. The workflow found both path AndroidStudio4.2 & AndroidStudio2021.1, then when use the "first" one (natural sort), which is the old for this case

**Comment by bchatard** [comment]
ok so let's check the bin because there is no reason to try this path
`cat $(which studio)
<img width="1367" alt="CleanShot 2022-01-31 at 10 41 53@2x" src="https://user-images.githubusercontent.com/829364/151771056-c65d3b4b-e5b2-4c42-9e8a-a27a74d4b857.png">
`

**Comment by AlexeyKorshun** [comment]
![Screenshot 2022-01-31 at 15 44 04](https://user-images.githubusercontent.com/7361026/151771319-98db515d-7eac-4c5e-a303-01736cb3a56c.png)

**Comment by bchatard** [comment]
thanks, so don't understand why the workflow try a path that doesn't exists...

**Comment by AlexeyKorshun** [comment]
It is a cache problem for product I think

**Comment by AlexeyKorshun** [comment]
I dropped alfy cache by myself, and it started work. Update cache variables in argv doesn't have an effect on cache, because maxAge was set.
