### ISSUE TITLE
Failed at the @bchatard/alfred-jetbrains@1.0.12 postinstall script

### ISSUE THREAD

**Issue by fedor1991** [bchatard/alfred-jetbrains#26]
Q | A
--- | ---
Workflow version | _latest_
OSX Version | _10.14.5_
Alfred Version | _4_
JetBrains Product/Version | _Idea / 2019.1_
Installation type | _Caskroom_

### Description
Can't install it with npm (_brew install node_). I used this before, but I decided to reinstall everything after upgrading to the alfred 4. I tried to delete npm and node completely and install again via brew, but it didn't help.

[logs.txt](https://github.com/bchatard/alfred-jetbrains/files/3265444/logs.txt)

**Comment by bchatard** [comment]
Same issue: #22 
The best workaround for now is in the comment: https://github.com/bchatard/alfred-jetbrains/issues/22#issuecomment-499025087
