### ISSUE TITLE
Is "source ~/.zshrc" really needed ?

### ISSUE THREAD

**Issue by cpoissonnier** [bchatard/alfred-jetbrains#271]
I just installed this workflow, and it is really going to help me in my daily work, thanks !

But the thing is that I realized that the `source ~/.zshrc` makes the workflow less reactive.

Is this really needed to make the workflow work? I updated the workflow on my local installation to have a reactive feedback, it might be cool to do it by default, no ?

Thanks again for your work :)

**Comment by bchatard** [comment]
Hi,

It was for sure, but maybe now not really. I'll try to remove it for testing in my env.

I'll update the ticket

**Comment by bchatard** [comment]
drop in latest release
