### ISSUE TITLE
about env: python: No such file or directory

### ISSUE THREAD

**Issue by hachikozjq** [bchatard/alfred-jetbrains#273]
### FAQ

- [X] Yes, my issue is not listed in [troubleshooting guide](https://github.com/bchatard/alfred-jetbrains/blob/main/doc/troubleshooting.md).
- [X] Yes, my issue is not listed in other issues.

### Describe the bug

see https://github.com/bchatard/alfred-jetbrains/issues/263

now I know why Idea project cannot be opened.

look at the following description

Starting with MacOS 12.3 Beta, Apple no longer has python2 built in and will not be able to properly install python2 on devices with either Intel chips or Apple chips. The cause is that the /usr/bin/python soft link cannot be deleted or overwritten properly.

so this problem is caused by the macOS system upgrade.
how to solve it?

### To Reproduce

see https://github.com/bchatard/alfred-jetbrains/issues/263

### Alfred Version

4.6.3

### Node Version

17.6.0

### NPM Version

8.5.1

### Jetbrains Product & Version

idea 2021.2

### Installation type

JetBrains ToolBox

### OS

macOS 12.3

**Comment by bchatard** [comment]
please do not open multiple issue for the same topic, I'll close this one. Update #263 with your latest information
