### ISSUE TITLE
Can not find new project after upgrade PHPStorm

### ISSUE THREAD

**Issue by bangnokia** [bchatard/alfred-jetbrains#275]
### FAQ

- [X] Yes, my issue is not listed in [troubleshooting guide](https://github.com/bchatard/alfred-jetbrains/blob/main/doc/troubleshooting.md).
- [X] Yes, my issue is not listed in other issues.

### Describe the bug

After upgrading PHPStorm from 2022.1.1 to 2022.1.2 via the Toolbox (which also happened from other old versions), my workflow can not find new projects anymore. It only shows the old projects which I opened in the last version. The only way I have to do is to uninstall all the PHPStorm and reinstall from scratch. Remove the library via npm uninstall is not working.

### To Reproduce

Update PHPStorm via Toolbox, open a new project, then search for it

### Expected behavior

It can find the new projects opened using the latest version

### Alfred Version

4.6.6

### Node Version

v16.15.0

### NPM Version

8.5.5

### Jetbrains Product & Version

PhpStorm 2022.1.2

### Installation type

JetBrains ToolBox

### OS

macOS 12.3

**Comment by bchatard** [comment]
this happen after upgrade, you should close all PHPStorm instance, open latest version to ensure that all config and `bin` has been updated.

If not, please check content of `~/Library/Application\ Support/JetBrains/PhpStorm2022.1/options/recentProjects.xml`

**Comment by bangnokia** [comment]
thank you so much, it works. Finally, I know why 😂. I delete that file, delete other PhpStormxxx folders, jb clean projects cache and it going well
