### ISSUE TITLE
IntelliJ not working

### ISSUE THREAD

**Issue by tofagerl** [bchatard/alfred-jetbrains#3]
Q | A
--- | ---
Workflow version | _1.0.1_
OSX Version | _10.14.4_
Alfred Version | _3.8.1_
JetBrains Product/Version | _IntelliJ / 2019.1_
Installation type | _JB Toolbox_

### Description
"idea" wasn't one of the original script filters for the workflow, and even after adding it manually (copied from PhpStorm) it doesn't work. 
There's no error, it originally couldn't find the idea shortcut, but I moved it and now it simply don't show any projects.

### Step to reproduce
type idea in Alfred, and nothing happens except IntelliJ shows up as an application. pstorm and wstorm show errors, as I don't have those installed, so I can't verify that those work either.

**Comment by bchatard** [comment]
@tofagerl Yes, my bad I release the . workflow without idea support...
I have an issue with the Community/Ultimate case.
Which version did you use, Community or Ultimate?

Thanks,

**Comment by tofagerl** [comment]
Ultimate

**Comment by bchatard** [comment]
@tofagerl please, take a look on the latest release

**Comment by tofagerl** [comment]
@bchatard It works on some projects, but doesn't show all projects that are shown in the toolbox dropdown. All projects in a subfolder I use for work are missing, for instance.

**Comment by bchatard** [comment]
@tofagerl thanks for your feedback, can you provide me a `.idea` folder of a project that doesn't appear in workflow?

**Comment by Stvad** [comment]
Does not work for me at all =\. Getting the following errow from wf:

```
TypeError: Cannot read property 'length' of null
    at getApplicationPath (/Users/sitalov/.nvm/versions/node/v11.1.0/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:56:13)
    at Object.get (/Users/sitalov/.nvm/versions/node/v11.1.0/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:73:31)
    at Object.<anonymous> (/Users/sitalov/.nvm/versions/node/v11.1.0/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:6:38)
```

-
JetBrains - Open Project - v3 1.0.3
Alfred 3.8.1
darwin x64 18.5.0

**Comment by bchatard** [comment]
@Stvad can you open an other issue please? And in this new issue, can you provide the result of the following command: `cat $(which idea)`?

**Comment by tofagerl** [comment]
@bchatard I can't really send work files, no. I discovered the parent directory of these projects had a .idea folder, though, and deleted it, and now I get this interesting error even after clearing cache:
`Error: ENOENT: no such file or directory, scandir '/Users/tom/dev/entur/.idea'
    at getFiles (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project/name.js:4:32)
    at Object.viaIml (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project/name.js:20:24)
    at Object.getProductName [as get] (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project/name.js:28:43)
    at buildItem (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project.js:7:28)
    at paths.forEach.path (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project.js:40:20)
    at Array.forEach (<anonymous>)
    at Object.getItems (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/project.js:39:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:12:23)`

**Comment by bchatard** [comment]
ok thanks I understand.

For error, it's fixed in latest release. Can you update your workflow?

**Comment by bchatard** [comment]
Another point, I didn't re-implement all previous feature. 
The missing case is the following:
https://github.com/bchatard/jetbrains-alfred-workflow/blob/master/src/lib/ProjectName.php#L52

I will add it soon!

**Comment by neetkee** [comment]
<img width="680" alt="image" src="https://user-images.githubusercontent.com/7801927/55942981-4c5eda80-5c4e-11e9-8a3e-9d9b88392697.png">
With version 1.6 I have some issues with displaying project names

**Comment by bchatard** [comment]
@neetkee can you provide your `.idea` directory or at least the following file `./idea/workspace.xml`?
It will help me to well test this case

**Comment by neetkee** [comment]
Sure, this is .idea directory from kotlin-dsl-example project
[kotlin-dsl-example.idea.zip](https://github.com/bchatard/alfred-jetbrains/files/3068029/kotlin-dsl-example.idea.zip)

**Comment by tofagerl** [comment]
@bchatard Just this visual bug left: 
<img width="522" alt="Screen Shot 2019-04-11 at 13 25 20" src="https://user-images.githubusercontent.com/781189/55953783-550add00-5c5d-11e9-8be4-9e1574220998.png">

**Comment by bchatard** [comment]
@tofagerl @neetkee can you check the latest release, it should fix this issue

**Comment by neetkee** [comment]
@bchatard It's working, thanks!

**Comment by tofagerl** [comment]
@bchatard Yep, you can close this bug. Thanks for all your work!
