### ISSUE TITLE
How can I set the right script path to this workflow

### ISSUE THREAD

**Issue by 521alice** [bchatard/alfred-jetbrains#300]
Use toolbox default setting for the script path， but the  follow error log coming

![popo_2023-01-16  16-11-40](https://user-images.githubusercontent.com/30821624/212629594-f132cf90-9ee0-45dd-8618-cf464ffe6c97.jpg)

#
`Error: Unable to find bin for IntelliJIdea. 
Search for bin named: idea
    at getApplicationPath (file:///opt/homebrew/
lib/node_modules/@bchatard/alfred-jetbrains/src/
findProduct.js:128:11)
    at findProduct (file:///opt/homebrew/lib/
node_modules/@bchatard/alfred-jetbrains/src/
findProduct.js:172:31)
    at file:///opt/homebrew/lib/node_modules/
@bchatard/alfred-jetbrains/src/index.js:16:17`

![image](https://user-images.githubusercontent.com/30821624/212630523-9f8a68f3-df1e-41b9-ad0c-40a2071142b5.png)

other products have the same issue

**Comment by awerenne** [comment]
Same issue
