### ISSUE TITLE
Add file actions

### ISSUE THREAD

**Issue by yihou** [bchatard/alfred-jetbrains#31]
Q | A
--- | ---
Workflow version | 1.0.12
OSX Version | 10.14.5
Alfred Version | 4.0.1
JetBrains Product/Version | PhpStorm / 2019.1
Installation type | npm

### Description
on using `⌘` + `\` on selected folder in finder, open with `Phpstorm` or other Jetbrains products does not work properly, hope there's file action that allows that.
It's helpful to open projects that are not part of the project list

### Step to reproduce
As describe in the description

**Comment by bchatard** [comment]
Hi 

Sorry I don't understand the issue.

Where did you use `⌘` + `\`? 
Can you put some screenshots / videos on the issue?

Thanks,

**Comment by yihou** [comment]
My bad, what I meant is `Actions` feature, in the picture below
![image](https://user-images.githubusercontent.com/10841650/59843380-0a0ef380-938b-11e9-905b-6b99d86df015.png)

Hope file action feature can be added in the workflow, so that we can open Jetbrains IDE on a targeted folder
![image](https://user-images.githubusercontent.com/10841650/59844334-362b7400-938d-11e9-99b4-138781daa51d.png)

**Comment by bchatard** [comment]
ok thanks for the feedback, I will try to look on this (or maybe you 😃 )

**Comment by yihou** [comment]
My pleasure, will create a pr once done.

**Comment by yihou** [comment]
The Arrangement a bit crazy, at the moment I just copy the `Run Script` and notification
![image](https://user-images.githubusercontent.com/10841650/59893160-944c6b80-940e-11e9-8706-3c32fef2b500.png)

**Comment by bchatard** [comment]
close by #32
