### ISSUE TITLE
Unable to 'Open Pycharm Project' when using 'JetBrains Toolbox'

### ISSUE THREAD

**Issue by Gabrielvon** [bchatard/alfred-jetbrains#327]
### FAQ

- [X] Yes, my issue is not listed in [troubleshooting guide](https://github.com/bchatard/alfred-jetbrains/blob/main/doc/troubleshooting.md).
- [X] Yes, my issue is not listed in other issues.

### Describe the bug

<img width="713" alt="image" src="https://github.com/bchatard/alfred-jetbrains/assets/8952869/25390041-384e-4f25-807c-8b2955c1f406">

It seems that the words not match with 'Pycharm CE' sine JetBrains Toolbox install 'Pycharm CE' named as 'Pycharm Community' in JetBrains Toolbox folder. 

However, 'pycharm' is still working for it detect the file in responding path.

<img width="707" alt="image" src="https://github.com/bchatard/alfred-jetbrains/assets/8952869/e2a31a76-963e-4c08-b5df-8becea5dbb69">

### To Reproduce

1. Install JetBrain Toolbox
2. Install Pycharm via JetBrain Toolbox and uninstall original Pycharm

### Alfred Version

5.1

### Workflow Version

2.0.2

### Node Version

v20.0.0

### NPM Version

9.6.7

### Jetbrains Product & Version

Pycharm Community 2023.1.2

### Installation type

JetBrains ToolBox

### OS

macOS 13.3

**Comment by bchatard** [comment]
Ok thanks for this precious feedback, so Jetbrains don't name products same if toolbox or not. I will look at it quickly

**Comment by Gabrielvon** [comment]
just updated. It seems have the same path error. I noticed that the prompt changed.

<img width="708" alt="Screenshot 2023-05-23 at 8 39 49 AM" src="https://github.com/bchatard/alfred-jetbrains/assets/8952869/5cd9befd-098f-4058-a424-2128d7978234">

Also I double check the path, and the binaries `pycahrm` does exists in `/usr/local/bin`

<img width="439" alt="Screenshot 2023-05-23 at 8 43 24 AM" src="https://github.com/bchatard/alfred-jetbrains/assets/8952869/2b478143-fd5c-4305-8c56-95f36b040c0a">

**Comment by bchatard** [comment]
hi,

just create new version with more logs

open Alfred debug bar in the workflow settings to locate your log file, then send it to me here

![CleanShot 2023-05-31 at 10 43 04@2x](https://github.com/bchatard/alfred-jetbrains/assets/829364/1b8fe6fc-26b8-48a0-9c38-bded1045aef4)

**Comment by Gabrielvon** [comment]
hi,

I did as you said and there are many lines so I upload it as attachment. Also, I wiped out some private information there which I think may not affect the debug.

[debug.log](https://github.com/bchatard/alfred-jetbrains/files/11645789/debug.log)

**Comment by bchatard** [comment]
with information available in log, there is no bin `pycharm` or `charm`

since you edit it, can you check in the original log file if bin is listed after this line "Looking in Directory: '/usr/local/bin'"

**Comment by Gabrielvon** [comment]
There is a line showed in the origin log indeed. In fact, I didn't remove any line as whole just replace some sensative words with "---". So, the line is actually found in the both original and edited version of the log.

<img width="588" alt="image" src="https://github.com/bchatard/alfred-jetbrains/assets/8952869/d959a395-771a-48b1-99b4-c53c940008f9">

**Comment by bchatard** [comment]
your bin are symlinked in `/usr/local/bin`? 

as mentioned, no bin are found by the script

**Comment by bchatard** [comment]
I meant the bin (charm, pycharm ans so on) in `/usr/local/bin`

**Comment by olliekennedy** [comment]
Hi there, I'm getting the same kind of problem.

I have a fresh M1 Max machine which I put Jetbrains Toolbox onto, then installed IntelliJ Ultimate using that.

I then performed the npm install command from the installation on the readme, then tried to use the launcher by calling alfred with idea. It didn't work ("Can't find settings path for IntelliJIdeaCommunity") so I repeated it with debug on. Here is the output:

```
[09:27:17.080] Logging Started...
[09:27:19.700] JetBrains - Open Project[[Script Filter](alfredpreferences:workflows%3Eworkflow%3E@bchatard-alfred-jetbrains-next%3E141026F3-CC2E-4808-BF5B-BC24CCA41438)] Queuing argument '(null)'
[09:27:19.880] JetBrains - Open Project[[Script Filter](alfredpreferences:workflows%3Eworkflow%3E@bchatard-alfred-jetbrains-next%3E141026F3-CC2E-4808-BF5B-BC24CCA41438)] Script with argv '(null)' finished
[09:27:19.885] JetBrains - Open Project[[Script Filter](alfredpreferences:workflows%3Eworkflow%3E@bchatard-alfred-jetbrains-next%3E141026F3-CC2E-4808-BF5B-BC24CCA41438)] {
  "items": [
    {
      "uid": "Can't find settings path for IntelliJIdeaCommunity",
      "title": "Can't find settings path for IntelliJIdeaCommunity",
      "match": "Can't find settings path for IntelliJIdeaCommunity Preferences]",
      "subtitle": "Please check if preferences 'IdeaIC' exists in [~/Library/Application Support/Google, ~/Library/Application Support/JetBrains, ~/Library/Preferences]",
      "arg": "Please check if preferences 'IdeaIC' exists in [~/Library/Application Support/Google, ~/Library/Application Support/JetBrains, ~/Library/Preferences]",
      "autocomplete": "Can't find settings path for IntelliJIdeaCommunity",
      "text": {
        "copy": "Please check if preferences 'IdeaIC' exists in [~/Library/Application Support/Google, ~/Library/Application Support/JetBrains, ~/Library/Preferences]",
        "largetype": "Can't find settings path for IntelliJIdeaCommunity"
      },
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      }
    },
    {
      "uid": "Debug: CLI version 0.0.14",
      "title": "Debug: CLI version 0.0.14",
      "match": "Debug: CLI version 0.0.14 0.0.14",
      "subtitle": "0.0.14",
      "arg": "0.0.14",
      "autocomplete": "Debug: CLI version 0.0.14",
      "text": {
        "copy": "0.0.14",
        "largetype": "Debug: CLI version 0.0.14"
      },
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertNoteIcon.icns"
      }
    },
    {
      "uid": "Debug: Log alfred_jetbrains_cli_2023-06-12.log",
      "title": "Debug: Log alfred_jetbrains_cli_2023-06-12.log",
      "match": "Debug: Log alfred_jetbrains_cli_2023-06-12.log alfred_jetbrains_cli_2023-06-12.log",
      "subtitle": "/var/folders/y2/zd___pdd18378y16nxs428hh0000gq/T/alfred_jetbrains_cli_2023-06-12.log",
      "arg": "/var/folders/y2/zd___pdd18378y16nxs428hh0000gq/T/alfred_jetbrains_cli_2023-06-12.log",
      "autocomplete": "Debug: Log alfred_jetbrains_cli_2023-06-12.log",
      "text": {
        "copy": "/var/folders/y2/zd___pdd18378y16nxs428hh0000gq/T/alfred_jetbrains_cli_2023-06-12.log",
        "largetype": "Debug: Log alfred_jetbrains_cli_2023-06-12.log"
      },
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/ProblemReport.icns"
      }
    },
    {
      "uid": "Debug: Took 12ms",
      "title": "Debug: Took 12ms",
      "match": "Debug: Took 12ms Started at: 2023-06-12T09:27:19.795066 || Ended at: 2023-06-12T09:27:19.808014",
      "subtitle": "Started at: 2023-06-12T09:27:19.795066 || Ended at: 2023-06-12T09:27:19.808014",
      "arg": "Started at: 2023-06-12T09:27:19.795066 || Ended at: 2023-06-12T09:27:19.808014",
      "autocomplete": "Debug: Took 12ms",
      "text": {
        "copy": "Started at: 2023-06-12T09:27:19.795066 || Ended at: 2023-06-12T09:27:19.808014",
        "largetype": "Debug: Took 12ms"
      },
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Clock.icns"
      }
    }
  ]
}
```

**Comment by bchatard** [comment]
@olliekennedy 

You "installed IntelliJ Ultimate", but you didn't configure the workflow to use this version: "Can't find settings path for **IntelliJIdeaCommunity**"

**Comment by jimmyn** [comment]
I'm facing the same issue

```
{
  "items": [
    {
      "uid": "Can't locate application for pyCharmCommunity",
      "title": "Can't locate application for pyCharmCommunity",
      "match": "Can't locate application for pyCharmCommunity JetBrains Toolbox]",
      "subtitle": "Please check if application '[PyCharm CE, PyCharm Community]' exists in [/Applications, ~/Applications, ~/Applications/JetBrains Toolbox]",
      "arg": "Please check if application '[PyCharm CE, PyCharm Community]' exists in [/Applications, ~/Applications, ~/Applications/JetBrains Toolbox]",
      "autocomplete": "Can't locate application for pyCharmCommunity",
      "text": {
        "copy": "Please check if application '[PyCharm CE, PyCharm Community]' exists in [/Applications, ~/Applications, ~/Applications/JetBrains Toolbox]",
        "largetype": "Can't locate application for pyCharmCommunity"
      },
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      }
    },
    {
      "uid": "Debug: CLI version 0.0.14",
      "title": "Debug: CLI version 0.0.14",
      "match": "Debug: CLI version 0.0.14 0.0.14",
      "subtitle": "0.0.14",
      "arg": "0.0.14",
      "autocomplete": "Debug: CLI version 0.0.14",
      "text": {
        "copy": "0.0.14",
        "largetype": "Debug: CLI version 0.0.14"
      },
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertNoteIcon.icns"
      }
    },
    {
      "uid": "Debug: Log alfred_jetbrains_cli_2023-06-23.log",
      "title": "Debug: Log alfred_jetbrains_cli_2023-06-23.log",
      "match": "Debug: Log alfred_jetbrains_cli_2023-06-23.log alfred_jetbrains_cli_2023-06-23.log",
      "subtitle": "/var/folders/38/lrd2zfns41b0wm2tgdgl2q2w0000gn/T/alfred_jetbrains_cli_2023-06-23.log",
      "arg": "/var/folders/38/lrd2zfns41b0wm2tgdgl2q2w0000gn/T/alfred_jetbrains_cli_2023-06-23.log",
      "autocomplete": "Debug: Log alfred_jetbrains_cli_2023-06-23.log",
      "text": {
        "copy": "/var/folders/38/lrd2zfns41b0wm2tgdgl2q2w0000gn/T/alfred_jetbrains_cli_2023-06-23.log",
        "largetype": "Debug: Log alfred_jetbrains_cli_2023-06-23.log"
      },
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/ProblemReport.icns"
      }
    },
    {
      "uid": "Debug: Took 15ms",
      "title": "Debug: Took 15ms",
      "match": "Debug: Took 15ms Started at: 2023-06-23T18:55:11.341970 || Ended at: 2023-06-23T18:55:11.357630",
      "subtitle": "Started at: 2023-06-23T18:55:11.341970 || Ended at: 2023-06-23T18:55:11.357630",
      "arg": "Started at: 2023-06-23T18:55:11.341970 || Ended at: 2023-06-23T18:55:11.357630",
      "autocomplete": "Debug: Took 15ms",
      "text": {
        "copy": "Started at: 2023-06-23T18:55:11.341970 || Ended at: 2023-06-23T18:55:11.357630",
        "largetype": "Debug: Took 15ms"
      },
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Clock.icns"
      }
    }
  ]
}
```

PyCharm is installed using Jetbrains ToolBox in 

```/Users/dmitriy/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-C/ch-0/231.9161.41```

**Comment by bchatard** [comment]
did you check the name of the app?
> Please check if application '[PyCharm CE, PyCharm Community]' exists in [/Applications, ~/Applications, ~/Applications/JetBrains Toolbox]

With 2 macOS, both with ToolBox, PyCharm Community application's name is not the same... Thanks JetBrains 😆 
One is "PyCharm Community" and this other is "PyCharm Community Edition"
Just publish a new version, this fix the issue on my side

**Comment by jimmyn** [comment]
@bchatard thanks! it works now 👍
