### ISSUE TITLE
Unable to save data for workflow 

### ISSUE THREAD

**Issue by ShubhamJ010** [bchatard/alfred-jetbrains#334]
### FAQ

- [X] Yes, my issue is not listed in [troubleshooting guide](https://github.com/bchatard/alfred-jetbrains/blob/main/doc/troubleshooting.md).
- [X] Yes, my issue is not listed in other issues.

### Describe the bug

Whenever trying to change the idea community to ultimate and hit the save button this following error showsup and the setting is not changed to Ultimate
`Unable to save data for workflow 'JetBrains - Open Project' (/us/local/lib/node_modules/@bchatard/alfred-jetbrains/info.plist)`

<img width="838" alt="image" src="https://github.com/bchatard/alfred-jetbrains/assets/40000538/d0031dfb-e35a-470f-a812-d188cc2152e9">

### To Reproduce

1. Go to configure workflow<br>
<img width="287" alt="image" src="https://github.com/bchatard/alfred-jetbrains/assets/40000538/41196cff-60c2-46fd-a52b-a5156140ea74"><br>
3. Change the community to Ultimate<br>
<img width="349" alt="image" src="https://github.com/bchatard/alfred-jetbrains/assets/40000538/0dcecac9-7992-4168-9330-f57f636f5169"><br>
4. Hit Save<br>
<img width="1170" alt="image" src="https://github.com/bchatard/alfred-jetbrains/assets/40000538/17bccb7d-e80e-48dd-a05e-a283d67b071e">

### Alfred Version

5.1.2

### Workflow Version

2.0.8

### Node Version

v18.12.1

### NPM Version

9.8.1

### Jetbrains Product & Version

IntelliJ IDEA 2023.2.1, build IU-232.9559.62.

### Installation type

Homebrew

### OS

macOS 13.3

**Comment by ShubhamJ010** [comment]
# Here are the answers please help
 
### How i installed it 
#### I did  `sudo npm install -g @bchatard/alfred-jetbrains`
and i need to use sudo cause it was showing it lacked perm
**Note : Node in My mac is installed using brew as well**
` alfred-jetbrains where node
/usr/local/bin/node
/opt/homebrew/bin/node
/usr/local/bin/node
/usr/local/bin/node
/usr/local/bin/node
/opt/homebrew/bin/node
/usr/local/bin/node
/usr/local/bin/node`


## Here are the permission on the file in `/us/local/lib/node_modules/@bchatard/alfred-jetbrains/`
![image](https://github.com/bchatard/alfred-jetbrains/assets/40000538/064c7bf7-e6f3-469c-b972-dd1f6d8c7c84)

## did you try to remove the worklfow and reinstall again?
Yes i did multiple times

**Comment by ShubhamJ010** [comment]
Ran this command and it worked 
`sudo chmod -R 777 /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/`

**Comment by bchatard** [comment]
The workflow should not be installed as root

you should not trust my code :D
