### ISSUE TITLE
search project bug 

### ISSUE THREAD

**Issue by cwl168** [bchatard/alfred-jetbrains#335]
### FAQ

- [X] Yes, my issue is not listed in [troubleshooting guide](https://github.com/bchatard/alfred-jetbrains/blob/main/doc/troubleshooting.md).
- [X] Yes, my issue is not listed in other issues.

### Describe the bug

I have a Java project called qf-agenttool. When I search with the keyword 'idea agent', it can be found, but when I search with 'tool', it cannot be found. Is this a bug and how should I deal with it?

### To Reproduce

no

### Alfred Version

5

### Workflow Version

2.0.9

### Node Version

v16.1.0

### NPM Version

7.11.2

### Jetbrains Product & Version

IntelliJ IDEA 2021.2 

### Installation type

Classic via .dmg

### OS

macOS 13.3

**Comment by bchatard** [comment]
hello,

search is managed through Alfred itself, The behavior can be changed on each product in alfred workflow, but it will be lost after a workflow update

![CleanShot 2023-11-15 at 15 20 52@2x](https://github.com/bchatard/alfred-jetbrains/assets/829364/57a60bcc-abe8-4b34-ab43-63a816e6d77d)

**Comment by cwl168** [comment]
<img width="759" alt="image" src="https://github.com/bchatard/alfred-jetbrains/assets/10610728/a53b568d-7cb4-4347-973e-0b8281e6d9d7">


I currently have this setup in the software Alfred. But my kind of scene to blur match idea project, really can not search.
