### ISSUE TITLE
Can not change Intellij Idea Edition to Ulimate.

### ISSUE THREAD

**Issue by cafefarm-johnny** [bchatard/alfred-jetbrains#336]
### FAQ

- [X] Yes, my issue is not listed in [troubleshooting guide](https://github.com/bchatard/alfred-jetbrains/blob/main/doc/troubleshooting.md).
- [X] Yes, my issue is not listed in other issues.

### Describe the bug

Tried to change from community to ultimate Intellij Idea Edition.
![SCR-20240105-mwvm](https://github.com/bchatard/alfred-jetbrains/assets/44919702/5ea5f3af-96c5-4c96-a597-452f6da8b308)

### To Reproduce

1. using workflow 2.0.7 version.
2. try to update 2.0.10 via npm. `sudo npm install -g @bchatard/alfred-jetbrains` 
3. open Alfred 5 settings.
4. click 'Workflows -> JetBrains - Open Project -> Configure Workflow...'
5. change Intellij Idea Edition

### Alfred Version

5.1.4

### Workflow Version

2.0.10

### Node Version

20.10.0

### NPM Version

10.2.3

### Jetbrains Product & Version

Intellij Idea Ultimate 2023.3.2

### Installation type

JetBrains ToolBox

### OS

macOS 14.1.1

**Comment by bchatard** [comment]
Hi, 
You shouldn't install the workflow with `sudo` because Alfred doesn't run as root so it can modify configuration file.
Try to remove completely the workflow then reinstall with your user.

**Comment by cafefarm-johnny** [comment]
Oh god... 
Thank you! 😊
