### ISSUE TITLE
Does not find PhpStorm application

### ISSUE THREAD

**Issue by stracker-phil** [bchatard/alfred-jetbrains#337]
### FAQ

- [X] Yes, my issue is not listed in [troubleshooting guide](https://github.com/bchatard/alfred-jetbrains/blob/main/doc/troubleshooting.md).
- [X] Yes, my issue is not listed in other issues.

### Describe the bug

Toolbox: ver 2.1.3
PhpStorm: ver 2023

I have 2 versions of PhpStorm: The last stable version (as a backup) and the latest version (for regular usage)
Toolbox installed PhpStorm with different names:
- PhpStorm 2023.3.2.app
- PhpStorm (Stable).app

The CLI tool does not recognize this and fails with the error "PhpStorm not found"

```
    {
      "uid": "Can't locate application for phpStorm",
      "title": "Can't locate application for phpStorm",
      "match": "Can't locate application for phpStorm Applications]",
      "subtitle": "Please check if application '[PhpStorm]' exists in [/Applications, ~/Applications, ~/Applications/JetBrains Toolbox, /Users/philipp/Applications]",
      "arg": "Please check if application '[PhpStorm]' exists in [/Applications, ~/Applications, ~/Applications/JetBrains Toolbox, /Users/philipp/Applications]",
      "autocomplete": "Can't locate application for phpStorm",
      "text": {
        "copy": "Please check if application '[PhpStorm]' exists in [/Applications, ~/Applications, ~/Applications/JetBrains Toolbox, /Users/philipp/Applications]",
        "largetype": "Can't locate application for phpStorm"
      },
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      }
    }
```

### To Reproduce

Install multiple versions of the same tool via the Toolbox.

<img width="439" alt="phpstorm-name" src="https://github.com/bchatard/alfred-jetbrains/assets/2669200/ea32f60a-3a2e-4564-b356-94c25a1f1f73">

### Expected behavior

I suggest adding a setting to define the preferred version of each tool

### Alfred Version

5.1.4

### Workflow Version

latest (?)

### Node Version

18.15.0

### NPM Version

10.3

### Jetbrains Product & Version

Toolbox: 2.1.3 / PhpStorm: 2023.3.2

### Installation type

JetBrains ToolBox

### OS

macOS 13.3

**Comment by stracker-phil** [comment]
I found a quick workaround:
Creating a symlink with name "PhpStorm" that points to the "PhpStorm 2023.3.2" app solves the problem for now. Let's see how this behaves after the next update

**Comment by bchatard** [comment]
hello,

Currently EAP versions aren't supported, I search for the exact name "PhpStorm".
So for now, you should create the symlink every time
