### ISSUE TITLE
Question about the behavior in toolbox 2: Filter proejct by partial name

### ISSUE THREAD

**Issue by DitongDing** [bchatard/alfred-jetbrains#338]
### FAQ

- [X] Yes, my issue is not listed in [troubleshooting guide](https://github.com/bchatard/alfred-jetbrains/blob/main/doc/troubleshooting.md).
- [X] Yes, my issue is not listed in other issues.

### Describe the bug

Background:

In my recent IntelliJ project list, there are many projects start with the same suffix (e.g. ABCProjectX, ABCProjectY, ABCProjectZ...). Previous I am able to reduce the candidate list by put partial name, however after update it's no longer working. 

I have updated the following, apologize I cannot remember the previous version:

* IntelliJ ultimate to latest
* Workflow updated
* JetBrain toolbox updated to latest.

Not sure if this is behavior change in idea CLI or something else.

### To Reproduce

Behavior before updating:

* When type in "idea X", only the ABCProjectX will show in the candidate list and I can proceed with opening the project directly.

Behavior after updating:

* When type in "idea X", the workflow will stop running and won't show the project list.

### Alfred Version

5.1.4

### Workflow Version

2.0.10

### Node Version

>14

### NPM Version

N/A

### Jetbrains Product & Version

IntelliJ 2023.3.3

### Installation type

Classic via .dmg

### OS

macOS 13.3

**Comment by bchatard** [comment]
Hi,

I change the behavior of searching, it's now handle by Alfred. In previous version I use [Fuse.js](https://www.fusejs.io/).

You can change this on workflow, but it will be reset on new version since it's not configurable.

![CleanShot 2024-02-11 at 15 54 00@2x](https://github.com/bchatard/alfred-jetbrains/assets/829364/e99c85d5-601b-4346-a589-c4f2b0a00899)

**Comment by DitongDing** [comment]
Thanks for the hint! I tested locally with some newly created projects, unforutnatley it's still not filtering by the partial name. Screenshot as following:

1. While typing "idea"
<img width="597" alt="Screenshot 2024-02-11 at 10 38 13" src="https://github.com/bchatard/alfred-jetbrains/assets/5326989/4ac9d966-4708-4adc-b16e-e3b671cd975c">

2. While typing "idea Proj" to filter project
<img width="586" alt="Screenshot 2024-02-11 at 10 38 22" src="https://github.com/bchatard/alfred-jetbrains/assets/5326989/ee7875af-5c37-43df-9575-82a6cb93cc8f">

3. While typing "idea ABC" to filter project
<img width="591" alt="Screenshot 2024-02-11 at 10 38 29" src="https://github.com/bchatard/alfred-jetbrains/assets/5326989/5908d071-b5fa-43b7-a38c-f56658b5dfd8">


4. While typing "idea e" to filter project: Interestingly the "light-edit" will be filtered as output
<img width="597" alt="Screenshot 2024-02-11 at 10 38 35" src="https://github.com/bchatard/alfred-jetbrains/assets/5326989/46802f6b-c1b1-4dc5-ab37-e5e1c6c8c17b">

Sharing current configuration as reference:
<img width="819" alt="Screenshot 2024-02-11 at 10 39 24" src="https://github.com/bchatard/alfred-jetbrains/assets/5326989/ac5b3b54-c2d0-4cac-8e6f-d0ea22926b5b">

Is it because this filter will only work with space separated words? Let me know if there is any other place I can look at for log/changes/etc. Much appreciate :-)

**Comment by bchatard** [comment]
This is Alfred behavior, you can take a look on documentation maybe it's more clear: https://www.alfredapp.com/help/workflows/inputs/script-filter/#alfred-filters-results

The `match` field mentioned contains project name and path to the project, so Alfred will search in this string.

**Comment by DitongDing** [comment]
Got it, thanks! Resolving the issue.
