### ISSUE TITLE
support hot key

### ISSUE THREAD

**Issue by radcat1987** [bchatard/alfred-jetbrains#339]
### FAQ

- [X] Yes, my issue is not listed in [troubleshooting guide](https://github.com/bchatard/alfred-jetbrains/blob/main/doc/troubleshooting.md).
- [X] Yes, my issue is not listed in other issues.
- [X] Yes, I reload my Alfred cache (with `reload`)

### Describe the bug

Wish hotkeys were supported

### To Reproduce

Wish hotkeys were supported

### Alfred Version

5.5[2257]

### Workflow Version

2.0.11

### Node Version

20.8.0

### NPM Version

10.1.0

### Jetbrains Product & Version

2024.1

### Installation type

Classic via .dmg

### OS

macOS 14.4.1

**Comment by bchatard** [comment]
Please read the doc
