### ISSUE TITLE
Workflow does not working in a specific situation.

### ISSUE THREAD

**Issue by npcdja** [bchatard/alfred-jetbrains#340]
### FAQ

- [X] Yes, my issue is not listed in [troubleshooting guide](https://github.com/bchatard/alfred-jetbrains/blob/main/doc/troubleshooting.md).
- [X] Yes, my issue is not listed in other issues.
- [X] Yes, I reload my Alfred cache (with `reload`)

### Describe the bug

When i use old version of Android Studio then workflow does not working. 

![do not work](https://github.com/bchatard/alfred-jetbrains/assets/64995944/ea1ad6b7-863e-4215-a652-06f7e0abe888)
Workflow does not working on Android Studio. The projects does not showing on Alfred prompt.

![alfred_jetbrains_cli](https://github.com/bchatard/alfred-jetbrains/assets/64995944/e798f512-26e1-4b1a-bbd5-cd956b76e50e)
So i tried execute alfred_jetbrains_cli through terminal. And i saw something weird about 'Use Directory'. 
Actually i'm using Android Studio 2023.2.1. but there are printed AndroidStudio2024.1 and empty items.

![toolbox](https://github.com/bchatard/alfred-jetbrains/assets/64995944/d9a3a16c-80fa-4496-9546-b5691a16142a)
![not insatlled directory](https://github.com/bchatard/alfred-jetbrains/assets/64995944/db288414-2399-485d-9282-39dc0278884b)
I never been installed newest version of Android Studio. but there were directory.

So i tried delete that directory but still not worked on Alfred and it will re-created in there.

### To Reproduce

1. install old version Android Studio.
2. using workflow on alfred.
3. does not show projects.

### Alfred Version

5.5

### Workflow Version

2.0.11

### Node Version

22.3.0

### NPM Version

10.8.1

### Jetbrains Product & Version

Android Studio Iguana 2023.2.1 Patch 1

### Installation type

JetBrains ToolBox

### OS

macOS 14.1.1

**Comment by bchatard** [comment]
thanks for your report.

I never saw this issue before, I have an idea for a fix. I will work on it asap.

After you remove the directory, did you try to flush the cache on Alfred? https://www.alfredapp.com/help/workflows/inputs/script-filter/json/#cache

**Comment by npcdja** [comment]
> thanks for your report.
> 
> I never saw this issue before, I have an idea for a fix. I will work on it asap.
> 
> After you remove the directory, did you try to flush the cache on Alfred? https://www.alfredapp.com/help/workflows/inputs/script-filter/json/#cache

Thank you for answer!

I tired according to your suggestion, and it solved. 

Newst version of Android Studio doesn't create a directory, studio script filter now working.

This is what i did.
1. ` cd /Users/{user}/Library/Application Support/Google`
2. `rm ./AndroidStudio2024.1`
3. typing `reload` on Alfred
4. enter 'Reload Alfred Cache'

**Comment by npcdja** [comment]
> > thanks for your report.
> > I never saw this issue before, I have an idea for a fix. I will work on it asap.
> > After you remove the directory, did you try to flush the cache on Alfred? https://www.alfredapp.com/help/workflows/inputs/script-filter/json/#cache
> 
> Thank you for answer!
> 
> I tried according to your suggestion, and it solved.
> 
> Newst version of Android Studio doesn't create a directory, studio script filter now working.
> 
> This is what i did.
> 
> 1. ` cd /Users/{user}/Library/Application Support/Google`
> 2. `rm ./AndroidStudio2024.1`
> 3. typing `reload` on Alfred
> 4. enter 'Reload Alfred Cache'

Hi, 

I was using a temporary fix for the issue, but the problem has reoccurred. It seems that Toolbox continuously creates new version directories, and due to the periodical updating of the Alfred cache, the issue appears again.

**Comment by npcdja** [comment]
Hi, Can i know plan for fix this issue? 🥹

**Comment by bchatard** [comment]
hello,

I start working on it, but my fix is still  not ready.
With the 2024.2 releases I can't reproduce your issue

I hope to find a fix quickly

**Comment by bchatard** [comment]
hi again,

please check latest version (2.1.1), it should resolve your issue

**Comment by npcdja** [comment]
It work on v2.1.1! Thank you!   👍
