### ISSUE TITLE
Command failed: /bin/sh -c which idea

### ISSUE THREAD

**Issue by VanOvermeire** [bchatard/alfred-jetbrains#53]
I have a similar problem as the one described in the closed issue https://github.com/bchatard/alfred-jetbrains/issues/48

Reinstalling fixed the issue yesterday. Today, it's back, see screenshot. 

<img width="1378" alt="Screenshot 2019-08-26 at 15 08 21" src="https://user-images.githubusercontent.com/10529492/63694077-eb5b2c00-c815-11e9-93c5-8ed526338724.png">

My node version is 12.5.0 and Alfred is 3.8.2

Any ideas? I don't feel like reinstalling every day or so. :/

**Comment by linuxjuggler** [comment]
@VanOvermeire I wish there is any other option, but based on our experience reinstalling fix it https://github.com/bchatard/alfred-jetbrains/issues/48#issuecomment-519813552

**Comment by bchatard** [comment]
Hi @VanOvermeire ,

Still no real idea about this issue. I will take a look on this more deeply. Maybe change the way I check the bin path.

**Comment by VanOvermeire** [comment]
Ok, thanks!

**Comment by it-noob** [comment]
I have also encountered the same problem. In the past two weeks, I have been unable to use it every few days and can only reinstall.

**Comment by tswestendorp** [comment]
> @VanOvermeire I wish there is any other option, but based on our experience reinstalling fix it [#48 (comment)](https://github.com/bchatard/alfred-jetbrains/issues/48#issuecomment-519813552)

Had the same issue, but indeed reinstalling fixed it

**Comment by terryupton** [comment]
I have the issue for PHPstorm

**Comment by AdamBD** [comment]
@bchatard which binary are we supposed to be pointing to?

**Comment by bchatard** [comment]
version 1.1.1 should fix the issue

**Comment by terryupton** [comment]
I have reinstalled version 1.1.1 and cleared cache and rebuilt the command line launcher in PHPstorm. However, I am now getting this error?

```
Your search - ``` TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string ... - did not match any documents.
```

**Comment by bchatard** [comment]
@terryupton please see #59
