### ISSUE TITLE
v1.1.1 PhpStorm - TypeError: path must be a string or Buffer

### ISSUE THREAD

**Issue by AdamBD** [bchatard/alfred-jetbrains#59]
Hi,

I updated to v1.1.1 and get the following error. I think the issue may be I am not setting the correct binary path in the Toolbox settings of intelliJ. Which I am not clear on / its not documented anywhere in the README 

```
TypeError: path must be a string or Buffer
    at getApplicationPath (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:84:25)
    at Object.get (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:115:31)
    at __dirname (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:15:38)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:61:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054
    at Generator.next (<anonymous>)
    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)
```

-
JetBrains - Open Project - v3 1.1.0
Alfred 4.0.3
darwin 18.5.0

**Comment by bchatard** [comment]
Hi @AdamBD,

I don’t understand the part about your bin path. Can you provide more information? (Bin path, node version etc)

Thanks

**Comment by orf** [comment]
I'm getting the same issue with PyCharm. Node v12.10.0. Bin path is `/usr/local/bin/charm`, nothing configured unusually. Just did a fresh `npm install`.

Fantastic workflow by the way!

**Comment by bchatard** [comment]
Hi,

Can you clone this repo: https://github.com/bchatard/issue_59
And send to me the result of the following commands:
* `node index.js` (edit `index.js` to update the `bin` variable if needed)
* `node --version`
* `which pycharm` (update with your bin name)

**Comment by orf** [comment]
Ahh, I see the issue here. PyCharm creates a launcher on MacOS by default at this path: `/usr/local/bin/charm`. It seems this workflow is looking for a binary called `pycharm`, not `charm`. 

```
$ node index.js
/usr/local/bin/charm
$ which charm
/usr/local/bin/charm
$ node --version
v12.10.0

**Comment by bchatard** [comment]
@orf so you only need to check this documentation: https://github.com/bchatard/alfred-jetbrains/blob/master/doc/customisation/product.md

**Comment by orf** [comment]
I'll update my config, but `charm` is the default binary name for PyCharm, I feel both should be checked or the default changed to `charm`. Also, clearly there is an underlying bug that means an error is thrown if the binary cannot be found.

Thanks for the link though!

**Comment by bchatard** [comment]
on my last PyCharm installation (on fresh macbook, with version 2019.1) the default bin name was `pycharm` (but maybe I'm wrong).

And you're right about the error message, I will release a new version to enhance this :)

**Comment by bchatard** [comment]
@orf please update to 1.1.2 (I don't know if the workflow still notify on new version)
