### ISSUE TITLE
Error: Can't find preference path for IntelliJIdea

### ISSUE THREAD

**Issue by aldiyarablyazov** [bchatard/alfred-jetbrains#62]
Typing `idea _projectname_` shows `Error: Can't find preference path for IntelliJIdea` instead of an option to open the project.

Full error log:
```
Error: Can't find preference path for IntelliJIdea
    at getPreferencePath (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:77:9)
    at Object.get (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:134:30)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:15:38
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:61:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)
    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054
    at Generator.next (<anonymous>)
    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)
    at kl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)
    at Object.u (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)

JetBrains - Open Project - v3 1.1.3
Alfred 4.0.4
darwin 18.7.0
```

**Screenshot**
<img width="562" alt="Screenshot 2019-09-18 at 16 51 29" src="https://user-images.githubusercontent.com/30394370/65159720-d0ef2980-da34-11e9-8623-f70a3bd5b409.png">

**Additional context**
macOS Mojave, Alfred 4.0.4. Installed via `$ npm install -g @bchatard/alfred-jetbrains`

**Comment by bchatard** [comment]
Hi,

Can you provide the result of the following command:
* `cat $(which idea)`

**Comment by aldiyarablyazov** [comment]
"/Users/myUsername/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/182.3684.101/IntelliJ IDEA CE.app/Contents/MacOS/idea" "$@"

**Comment by bchatard** [comment]
Please check documentation about customization, you need to change the configuration to use CE edition

**Comment by aldiyarablyazov** [comment]
Dear Brice,

Do you think you could help me (and probably many others) out and take some time out of your day to create a more comprehensive guide on how to set up the customisation so that your Alfred workflow can work with IntelliJ CE? I really like the idea of this neat workflow that you’ve created and would like to use it if I can, but all it’s doing is throwing errors on my end (i.e. Reference error: bin is not defined) and I know it’s probably my fault (for not setting it up right), but I would really appreciate if you could clear this up.

Best regards,

Aldiyar

**Comment by bchatard** [comment]
Hi @aldiyarablyazov,

You're right, the documentation is not very detailed. Can you please list all points of the documentation that is not clear for you, and I will try to explain it more clearly.

BTW, I'm thinking of changing the way how I manage the different version of the same product (wip for now)

**Comment by aldiyarablyazov** [comment]
Hello Brice,

Thank you for taking my words into consideration. On the topic of how the documentation could be clearer, perhaps you could move the customisation section within the installation section as it’s necessary for the workflow to function properly. Secondly, as well as offering examples, perhaps a step-by-step guide on how to set up the customisation files up properly so it works well with all versions of JetBrains software. Of course, a version of the workflow that has these already set-up by default or a .alfredworkflow file is also an option.

**Comment by bchatard** [comment]
@aldiyarablyazov 

I update the documentation to be more clear on the customization part. 
I also update the workflow to simplify the customization of the used product edition.
