### ISSUE TITLE
Allow other binaries configuration

### ISSUE THREAD

**Issue by mathieutu** [bchatard/alfred-jetbrains#7]
Q | A
--- | ---
Workflow version | _1.0.0_
OSX Version | _10.14.4_
Alfred Version | _3.8_
JetBrains Product/Version | _PhpStorm / 2019.1_
Installation type | _JB Toolbox_

### Description
Hi, 
My binaries for webstorm and phpstorm are `wstorm` and `pstorm`. 
It could be nice to allow an easy configuration of that.

Thanks.

**Comment by bchatard** [comment]
@mathieutu Yes, it's on my todo list: https://github.com/bchatard/alfred-jetbrains/blob/master/src/product.js#L8

Workaround
Maybe you can edit the file `products.json` in your workflow directory (`/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/products.json` - depends on your node installation)

**Comment by mathieutu** [comment]
Yeah, It's how I made it for now, but it was just to let you (and the other people interested) know.

**Comment by bchatard** [comment]
@mathieutu if can test the new release, I try to introduce this feature. Thanks

**Comment by mathieutu** [comment]
It works perfectly, thanks!
