### ISSUE TITLE
Error: Unable to find bin for IntelliJIdea. Search for bin named: idea

### ISSUE THREAD

**Issue by a827871781** [bchatard/alfred-jetbrains#73]
![image](https://user-images.githubusercontent.com/33977126/66805945-d9198680-ef58-11e9-80e5-045dd10bb017.png)

![image](https://user-images.githubusercontent.com/33977126/66806046-1d0c8b80-ef59-11e9-9efd-6a944281d5dd.png)

 How can I solve this problem?

**Comment by bchatard** [comment]
Hi @a827871781 

* did you create the shell script (see [doc](https://github.com/bchatard/alfred-jetbrains#init-shell-script))?
* can you check if the shell script works fine via your Terminal application?
* which version of IntelliJIdea did you use (community/educational/ultimate)?

**Comment by a827871781** [comment]
The script is okay,
Open the idea by running the script via Terminal,
ultimate

> Hi @a827871781
> 
> * did you create the shell script (see [doc](https://github.com/bchatard/alfred-jetbrains#init-shell-script))?
> * can you check if the shell script works fine via your Terminal application?
> * which version of IntelliJIdea did you use (community/educational/ultimate)?



> Hi @a827871781
> 
> * did you create the shell script (see [doc](https://github.com/bchatard/alfred-jetbrains#init-shell-script))?
> * can you check if the shell script works fine via your Terminal application?
> * which version of IntelliJIdea did you use (community/educational/ultimate)?

The script is okay,
Open the idea by running the script via Terminal,
ultimate

**Comment by a827871781** [comment]
> 嗨@ a827871781
> 
> * 您是否创建了 shell 脚本（请参阅[doc](https://github.com/bchatard/alfred-jetbrains#init-shell-script)）？
> * 您可以通过终端应用程序检查 shell 脚本是否工作正常吗？
> * 您使用了哪个版本的 IntelliJIdea（社区 / 教育 / 最终版本）？

The script is okay,
Open the idea by running the script via Terminal,
ultimate

**Comment by bchatard** [comment]
thanks,

* can you check your PATH environment variable (`echo ${PATH}` in your shell)?
* can you output the content of the `idea` bin?

Your bin are located in `/usr/local/bin/rider`?

**Comment by a827871781** [comment]
> thanks,
> 
> * can you check your PATH environment variable (`echo ${PATH}` in your shell)?
> * can you output the content of the `idea` bin?
> 
> Your bin are located in `/usr/local/bin/rider`?

 
![image](https://user-images.githubusercontent.com/33977126/66814488-3cabb000-ef69-11e9-9ba7-1ee26a185111.png)

thanks,

open -a "/Users/syz/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/192.6817.14/IntelliJ IDEA.app/Contents/MacOS/idea" "$@"

**Comment by bchatard** [comment]
can you do the following command: `which idea`

**Comment by a827871781** [comment]
> which idea

![image](https://user-images.githubusercontent.com/33977126/66814790-c2c7f680-ef69-11e9-99f5-5e5ce91b8c8c.png)

**Comment by bchatard** [comment]
so the issue is about your bin. It's not in your `PATH`. As mention before the location is in `/usr/local/bin/rider`. It should be in `/usr/local/bin/`

**Comment by a827871781** [comment]
> so the issue is about your bin. It's not in your `PATH`. As mention before the location is in `/usr/local/bin/rider`. It should be in `/usr/local/bin/`

Thank you so much, the problem is solved.

![image](https://user-images.githubusercontent.com/33977126/66815249-7fba5300-ef6a-11e9-9884-59175d5cad1a.png)

**Comment by bchatard** [comment]
top! you're welcome

**Comment by ahmeed83** [comment]
If it doesn't work on /usr/local/bin. That's means that the toolbox doesn't have permission to this dir. I solved by creating a new dir "bin" and assign the toolbox to it. %HOME%/bin

**Comment by rahelhabacker** [comment]
> Hi @a827871781
> ...
> * can you check if the shell script works fine via your Terminal application?

@bchatard that helped me solve it, thanks!
