### ISSUE TITLE
Can't find preference path

### ISSUE THREAD

**Issue by yuzhg** [bchatard/alfred-jetbrains#79]
**Describe the bug**
After installed the workflow and try follow up the customization guide, I still cannot make it work.

Error log:

18:55:26.979] JetBrains - Open Project - v3[Script Filter] Queuing argument ''
[18:55:27.337] JetBrains - Open Project - v3[Script Filter] Script with argv '' finished
[18:55:27.345] ERROR: JetBrains - Open Project - v3[Script Filter] Code 1: {
	"items": [
		{
			"title": "Error: Can't find preference path for /.config/alfred-jetbrains/custom.json\n    at getPreferencePath (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:80:9)\n    at Object.get (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:137:30)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:15:38\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:61:3)\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054\n    at Generator.next (<anonymous>)\n    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)\n    at kl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)\n    at Object.u (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nError: Can't find preference path for /.config/alfred-jetbrains/custom.json\n    at getPreferencePath (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:80:9)\n    at Object.get (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:137:30)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:15:38\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:61:3)\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054\n    at Generator.next (<anonymous>)\n    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)\n    at kl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)\n    at Object.u (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)\n```\n\n-\nJetBrains - Open Project - v3 1.1.4\nAlfred 4.0.5\ndarwin 18.7.0",
				"largetype": "Error: Can't find preference path for /.config/alfred-jetbrains/custom.json\n    at getPreferencePath (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:80:9)\n    at Object.get (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/product.js:137:30)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:15:38\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/src/index.js:61:3)\n    at Object.<anonymous> (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:251206)\n    at /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245054\n    at Generator.next (<anonymous>)\n    at bl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:245412)\n    at kl (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:247659)\n    at Object.u (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/esm/esm.js:1:287740)"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}

**Additional context**

My customized file is under here:
$ pwd
/Users/{my username}

$ ls .config/alfred-jetbrains/custom.json
.config/alfred-jetbrains/custom.json

$ cat  .config/alfred-jetbrains/custom.json
{
  "IdeaCE": {
    "preferences": "IdeaIC",
    "bin": "idea"
  },
  "IdeaIE": {
    "preferences": "IdeaIC",
    "bin": "idea"
  },
  "IdeaUE": {
    "preferences": "IdeaIC",
    "bin": "idea"
  }
}

I'm using community version of idea.

my setting:
![image](https://user-images.githubusercontent.com/1552319/67852365-3f9cc800-fb47-11e9-9148-a2093d5f1923.png)

I've tried to change the path to :
.config/alfred-jetbrains/custom.json or .config/alfred-jetbrains/custom.json, both have the same issue.

Could you please help to take a look. Thanks a lot!

**Comment by bchatard** [comment]
@yuzhg 

it's an issue in my documentation :'( I just update it.

in `jb_preferences_intellijidea` put `IntelliJIdea` or `IdeaIC` or `IdeaIE`

**Comment by yuzhg** [comment]
Great, now it works! Thanks for the effort, this is one of the most important workflow I'm depends on in my every working day :)
