### ISSUE TITLE
Workflow not compatible with Alfred 3.8.5

### ISSUE THREAD

**Issue by ranjitparva** [bchatard/alfred-jetbrains#80]
**Describe the bug**
After I installed the workflow and clicked on the workflow in the workflow viewer, the view says "Workflow incompatible. Please update to the lastest version of Alfred"

<img width="402" alt="Screen Shot 2019-11-04 at 7 59 21 PM" src="https://user-images.githubusercontent.com/1586527/68177588-a3efcb00-ff3d-11e9-9b33-b647f7b48fd4.png">

**Comment by bchatard** [comment]
hi @pranjit101 ,

Can you uninstall the workflow and try to install this version: `npm install -g @bchatard/alfred-jetbrains@1.0.12`.

If it works, can you remove it and try the folowing version: `npm install -g @bchatard/alfred-jetbrains@1.1.1`

**Comment by pranjit101** [comment]
That worked. Thanks for the quick reply

**Comment by bchatard** [comment]
@pranjit101 with which version? 

because I need to know when the Alfred 3 compatibiltiy has been breaked, and fix it

thanks :)

**Comment by pranjit101** [comment]
Both versions worked. Looks the version after @1.1.1 broke the compatibility.

**Comment by bchatard** [comment]
can I ask you to test other versions?
* `npm install -g @bchatard/alfred-jetbrains@1.1.2`
* `npm install -g @bchatard/alfred-jetbrains@1.1.3`
* `npm install -g @bchatard/alfred-jetbrains@1.1.4`

**Comment by pranjit101** [comment]
1.1.3 worked but 1.1.4 didn't.

**Comment by ArchCST** [comment]
Same here, 1.1.3 works, 1.1.4 not.
Alfred version 3.8.6.

**Comment by pqrth** [comment]
FYI, I had to downgrade to 1.1.3 as well, but the project search is affected by #126. So, I applied #127's [diff](https://github.com/bchatard/alfred-jetbrains/pull/127.diff) to make it work.
