### ISSUE TITLE
lock is invalid when typing lock

### ISSUE THREAD

**Issue by KingWang93** [bchatard/alfred-jetbrains#88]

**Comment by KingWang93** [comment]
alfred version：3.6

**Comment by bchatard** [comment]
can you provide more information? screenshot etc

**Comment by KingWang93** [comment]
![image](https://user-images.githubusercontent.com/17794023/69488962-a2665280-0eac-11ea-8452-36f7052dd8fe.png)
nothing happened after typing enter

**Comment by KingWang93** [comment]
another problem, alfred cannot recognize new projects when I open new projects using alfred

**Comment by bchatard** [comment]
please read the documentation : https://github.com/bchatard/alfred-jetbrains#how-to-use
You need to open alfred, then the keyword of the product you want to use (ex: `pstorm`), and then the project name
