### ISSUE TITLE
intellij idea 2019.3 not working

### ISSUE THREAD

**Issue by myl2ning** [bchatard/alfred-jetbrains#91]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

Q | A
--- | ---
Workflow version | _1.2.0_
OSX Version | _10.14.6_
Alfred Version | _4.0.5_
JetBrains Product/Version | _Intellij Idea / 2019.3_
Installation type | _classic .dmg_
Node version | _10.8.0_
NPM version | _6.12.0_

**Additional context**

**Comment by bchatard** [comment]
hi @myl2ning 

did you have some error messages?
I update idea, webstorm & phpstorm yesterday and everything works fine

**Comment by myl2ning** [comment]
> hi @myl2ning
> 
> did you have some error messages?
> I update idea, webstorm & phpstorm yesterday and everything works fine

where can I find the error messages? I can open project if the idea is not running, but if I open another project if the idea is running, nothing happened except the "open xx" notification.

**Comment by myl2ning** [comment]
I re-init the shell script and it works fine now, @bchatard thanks

**Comment by bchatard** [comment]
yes after an upgrade with "classic .dmg" you need to re-create the shell script (not automatically updated by the product). I will update the documentation to describe this case. Thanks for your feedback
