### ISSUE TITLE
Intellij Idea only can open only one project

### ISSUE THREAD

**Issue by evancyz** [bchatard/alfred-jetbrains#93]
Hello，My Intellij Idea Version is ：2019.03

I want open multiple project,but when i open one project,the other is invalid.

Is there a solution to solve this question?

**Comment by bchatard** [comment]
hi @evancyz 

did you update to 2019.3? did you update your shell script after the update?

**Comment by lchecho** [comment]
> hi @evancyz
> 
> did you update to 2019.3? did you update your shell script after the update?

Hi, I have the same question. if one project exists, I can't open another one in a new window, Phpstorm version 2019.3. It works well on version 2019.2.

**Comment by bchatard** [comment]
@lchecho 
did you update your shell script after the update?
can you please put the content of your script here?

**Comment by lchecho** [comment]
@bchatard Sorry for disturbing you...I updated my shell script after the update and the question appeared.But when I update the shell script again today, It works well now!0.0...Thank you so much!

**Comment by bchatard** [comment]
@evancyz any updates?

**Comment by evancyz** [comment]
i update the script. it works
thanks



---Original---

**Comment by cristiangrojas** [comment]
I'm facing this same issue with WebStorm 2020.2

I've installed Alfred yesterday so I'm running latest version of everything.

What's the script I should update? I don't understand.

**Comment by mihan007** [comment]
I also face to this issue. If it closed then PhpStorm open chosen project correctly. If it opened then it just activate window with opened project but not with chosen one. 

I'm using PhpStorm 2020.3 and generate pstorm cli from menu. I did some hack to make it work. At the bottom of pstorm script I replaced
```
ide_args = process_args(sys.argv)
if not try_activate_instance(ide_args):
    start_new_instance(ide_args)
```

with just
```
ide_args = process_args(sys.argv)
start_new_instance(ide_args)
```

it's not perfect but it works

**Comment by mihan007** [comment]
oh, sorry. I just totally remove pstorm script and generate new one from PhpStorm main menu. And it starts work like a charm. 

So just do ```rm /usr/local/bin/pstorm``` and then 
![image](https://user-images.githubusercontent.com/939122/102660131-97532400-418b-11eb-8101-cfb2bc9bab3e.png)
