### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by smeingast** [bchatard/alfred-jetbrains#95]
**Describe the bug**
Upon running the install command, I get the following error messages:

'Error: Permission denied to read Alfred preferences at location /Users/stefan/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n    at module.exports (/opt/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/resolve-alfred-prefs/index.js:44:9)'

I checked the location and I don't even have the file 'com.runningwithcrayons.Alfred-Preferences-3.plist' in this directory. The file I have is 'com.runningwithcrayons.Alfred-Preferences.plist'. Is there perhaps something wrong with my Alfred settings?

Q | A
--- | ---
Workflow version | latest
OSX Version | _10.15.2_
Alfred Version | _4.0.6_
JetBrains Product/Version | _PyCharm / 2019.3_
Node version | _10.17.0_
NPM version | _6.13.1_

**Comment by bchatard** [comment]
Hi @smeingast 

sorry for the late reply. Can you try to create the missing file (just an empty one) and try again to re-install?

**Comment by yulutongfei** [comment]
> Hi @smeingast
> 
> sorry for the late reply. Can you try to create the missing file (just an empty one) and try again to re-install?
It doesn't work

**Comment by china-shang** [comment]
I try 
`touch /Users/test/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist`
And then ` npm install -g @bchatard/alfred-jetbrains`
But  it doesn't work

```
> @bchatard/alfred-jetbrains@1.2.1 postinstall /usr/local/lib/node_modules/@bchatard/alfred-jetbrains
> alfy-init

Error: Command failed with exit code 1 (EPERM): alfred-link
    at makeError (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/alfy/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/alfy/node_modules/execa/index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/alfy/init.js:7:3 {
  command: 'alfred-link',
  exitCode: 1,
  exitCodeName: 'EPERM',
  stdout: '',
  stderr: 'Error: Permission denied to read Alfred preferences at location /Users/test/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n' +
    '    at module.exports (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/resolve-alfred-prefs/index.js:44:9)',
  all: 'Error: Permission denied to read Alfred preferences at location /Users/test/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n' +
    '    at module.exports (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/resolve-alfred-prefs/index.js:44:9)',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  signal: undefined
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @bchatard/alfred-jetbrains@1.2.1 postinstall: `alfy-init`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @bchatard/alfred-jetbrains@1.2.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```


Q | A
-- | --
Workflow version | latest
OSX Version | 10.15.2
Alfred Version | 4.0.6
JetBrains Product/Version | PyCharm / 2019.3
Node version | 12.16.1
NPM version | 6.13.4

**Comment by china-shang** [comment]
Whether it is related to this configuration ？
![image](https://user-images.githubusercontent.com/17249688/76144909-a74bbc80-60bf-11ea-8c1a-3b626538b685.png)

**Comment by china-shang** [comment]
https://github.com/sindresorhus/alfy/issues/110

**Comment by bchatard** [comment]
hello,
I'm using Alfy to manage this workflow, can you try another one on this list: https://github.com/sindresorhus/alfy/#users

if the problem persist maybe open an issue on Alfy repo

**Comment by AdamNSmith** [comment]
I'm getting the same error message on install. It's because I have my Alfred preferences in a non-standard location so they can be backed up and synced across machines.
https://www.alfredapp.com/help/advanced/sync/

@bchatard Is it possible to install using a non-standard Alfred preferences path? Thanks! :)

**Comment by bchatard** [comment]
hi @AdamNSmith 

I'm also using a custom location for preferences.

Can you try another workflow (see previous comment)?

**Comment by AdamNSmith** [comment]
I just tried to install another workflow from Alfy and got the same error. I'll look into more over there and report back what I find.

**Comment by jenkinv** [comment]
> Hi @smeingast
> 
> sorry for the late reply. Can you try to create the missing file (just an empty one) and try again to re-install?

i have the same error and have tried to touch the missing file , but doesn't work. Any other way to solve it ? thank you

**Comment by chenminhua** [comment]
same issue

**Comment by chenminhua** [comment]
I guess the file should be /Users/admin/Library/Preferences/com.runningwithcrayons.Alfred-Preferences.plist, so, it's should be file path issue.
I think we can work around this by create a softlink. But a pull request to cover this would be better.

**Comment by chenminhua** [comment]
in this dependency file https://github.com/SamVerschueren/resolve-alfred-prefs/blob/master/index.js, the preference file path is hardcoded.

**Comment by jenkinv** [comment]
> in this dependency file https://github.com/SamVerschueren/resolve-alfred-prefs/blob/master/index.js, the preference file path is hardcoded.

thks for your reply,but this is not the cause.the index.js is dealing with alfred 4 and 3.my version is 4 and the file is just there,but npm cannot have permission to read it. i guess there maybe some problem deeply.as now,i have worked around by :1.download source (dir1) 2.sudo npm install -g (failed.ignore ) 3.create soft link from workflow dir to dir1

**Comment by chenminhua** [comment]
it looks like an issue from alfred-link; https://github.com/SamVerschueren/alfred-link/issues/22
Some other workflows created by alfy have the same problem.

**Comment by FrankBian** [comment]
same error


```
Franks-MacBook-Pro-2:~ frankbian$ sudo npm install -g @bchatard/alfred-jetbrains

> fast-xml-parser@3.17.4 postinstall /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/fast-xml-parser
> node tasks/postinstall.js || exit 0

Love fast-xml-parser? Check https://amitkumargupta.work for more projects and contribution.


> @bchatard/alfred-jetbrains@1.4.0 postinstall /usr/local/lib/node_modules/@bchatard/alfred-jetbrains
> alfy-init

Error: Command failed with exit code 1 (EPERM): alfred-link
    at makeError (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/alfy/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/alfy/node_modules/execa/index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/alfy/init.js:7:3 {
  command: 'alfred-link',
  exitCode: 1,
  exitCodeName: 'EPERM',
  stdout: '',
  stderr: 'Error: Permission denied to read Alfred preferences at location /Users/frankbian/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n' +
    '    at module.exports (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/resolve-alfred-prefs/index.js:44:9)',
  all: 'Error: Permission denied to read Alfred preferences at location /Users/frankbian/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n' +
    '    at module.exports (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/resolve-alfred-prefs/index.js:44:9)',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  signal: undefined
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @bchatard/alfred-jetbrains@1.4.0 postinstall: `alfy-init`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @bchatard/alfred-jetbrains@1.4.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/frankbian/.npm/_logs/2020-11-03T10_00_45_867Z-debug.log
```

**Comment by kelvinchanjl** [comment]
> 同样的错误
> 
> ```
> Franks-MacBook-Pro-2:~ frankbian$ sudo npm install -g @bchatard/alfred-jetbrains
> 
> > fast-xml-parser@3.17.4 postinstall /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/fast-xml-parser
> > node tasks/postinstall.js || exit 0
> 
> Love fast-xml-parser? Check https://amitkumargupta.work for more projects and contribution.
> 
> 
> > @bchatard/alfred-jetbrains@1.4.0 postinstall /usr/local/lib/node_modules/@bchatard/alfred-jetbrains
> > alfy-init
> 
> Error: Command failed with exit code 1 (EPERM): alfred-link
>     at makeError (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/alfy/node_modules/execa/lib/error.js:59:11)
>     at handlePromise (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/alfy/node_modules/execa/index.js:112:26)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at async /usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/alfy/init.js:7:3 {
>   command: 'alfred-link',
>   exitCode: 1,
>   exitCodeName: 'EPERM',
>   stdout: '',
>   stderr: 'Error: Permission denied to read Alfred preferences at location /Users/frankbian/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n' +
>     '    at module.exports (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/resolve-alfred-prefs/index.js:44:9)',
>   all: 'Error: Permission denied to read Alfred preferences at location /Users/frankbian/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n' +
>     '    at module.exports (/usr/local/lib/node_modules/@bchatard/alfred-jetbrains/node_modules/resolve-alfred-prefs/index.js:44:9)',
>   failed: true,
>   timedOut: false,
>   isCanceled: false,
>   killed: false,
>   signal: undefined
> }
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! @bchatard/alfred-jetbrains@1.4.0 postinstall: `alfy-init`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the @bchatard/alfred-jetbrains@1.4.0 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/frankbian/.npm/_logs/2020-11-03T10_00_45_867Z-debug.log
> ```

有处理方法吗

**Comment by artem-krutov** [comment]
Changing the owner of npm's directories helped for me: https://stackoverflow.com/questions/47252451/permission-denied-when-installing-npm-modules-in-osx

**Comment by clonylu** [comment]
Try not do `sudo npm install -g`, follow [this guideline](https://stackoverflow.com/questions/48910876/error-eacces-permission-denied-access-usr-local-lib-node-modules) to configure npm to use a user directory. Then run `npm install -g`. 
 This solved the problem for me, although I don't fully understand the permission issue caused by running `sudo`.

**Comment by gengjiawen** [comment]
You can try yarn. `yarn global add @bchatard/alfred-jetbrains`

**Comment by lvliangxiong** [comment]
> You can try yarn. `yarn global add @bchatard/alfred-jetbrains`

this works for me
