### ISSUE TITLE
Not Opening Projects in Alfred 4 PhpStorm 2019.3.1

### ISSUE THREAD

**Issue by Maybach91** [bchatard/alfred-jetbrains#97]
**Describe the bug**
I just installed the newest Alfred Version (4.0.7) and the newest PhpStorm Version (2019.3.1) and ran `npm install -g @bchatard/alfred-jetbrains`. 

**To Reproduce**
1. Alfred Shortcut
2. Type 'pstorm PROJECT'
3. Hit enter
4. Notification from Toolbox visible
5. No project nor app were opened

**Expected behavior**
Opens the desired project

Q | A
--- | ---
Workflow version | _1.0.0_
OSX Version | _10.14.6_
Alfred Version | _4.0.7_
JetBrains Product/Version | _PhpStorm / 2019.3.1_
Installation type | _JB Toolbox_
Node version | _10.12.0_
NPM version | _6.8.0_

**Comment by bchatard** [comment]
hi @Maybach91 

Projects list contains your project?
The PhpStorm shell script is working? (test in bash/zsh)

**Comment by Maybach91** [comment]
Hej @bchatard 

thanks for getting back!

Yes, the script is showing my projects and after hitting enter the Notification pops up.

How can i run the Script?

You mean this script? Create a file test.sh and run it via sh test.sh in terminal, right? 
```
if [[ -n "{query}" ]]; then
	QUERY="{query}"
	BIN=${jb_bin}
	PROJECT_NAME=${jb_project_name}

	$(${BIN} "${QUERY}")

    echo ${PROJECT_NAME}
fi
```

**Comment by bchatard** [comment]
the script is installed by the toolbox, so you only need to do the following commands:
```shell script
$ cd /path/to/a/project
$ phpstorm .
```
NB: `phpstorm` seems to be default shell script name, but sometimes it's `pstorm`. So if you have a `command not found` error try with `pstorm .`

**Comment by Maybach91** [comment]
Hej @bchatard thanks for your response! I figured out, the shell script is not working because it's looking for an Application named `Phpstorm 2.app` which not exists anymore. I had a time where I had 2 different Phpstorm Version installed. Do you know how to fix this?

**Comment by bchatard** [comment]
hi @Maybach91 

you only need to recreate the shell script within PhpStorm
https://github.com/bchatard/alfred-jetbrains#init-shell-script

**Comment by Maybach91** [comment]
Thanks! That fixed it. I didnt know why i didnt saw/did it. :D @bchatard
